# Titanic

In [1]:
import pandas as pd
train_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/train.csv"
train = pd.read_csv(train_url)
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [2]:
test_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/test.csv"
test = pd.read_csv(test_url)
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [3]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [4]:
train["Age"].mode()

0    24.0
dtype: float64

# T4

In [5]:
train["Age"] = train["Age"].fillna(train["Age"].mode()[0])

In [6]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   28.566970    0.523008   
std     257.353842    0.486592    0.836071   13.199572    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   24.000000    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [7]:
print(pd.unique(train["Embarked"]))
print(train["Embarked"].isna().sum())

['S' 'C' 'Q' nan]
2


# T5

In [8]:
train.loc[train["Embarked"] == "S", "Embarked"] = 0
train.loc[train["Embarked"] == "C", "Embarked"] = 1
train.loc[train["Embarked"] == "Q", "Embarked"] = 2
train["Embarked"] = train["Embarked"].fillna(train["Embarked"].mode()[0])

In [9]:
print(pd.unique(train["Sex"]))

['male' 'female']


In [10]:
train.loc[train["Sex"] == "male", "Sex"] = 0
train.loc[train["Sex"] == "female", "Sex"] = 1

# T6

In [11]:
import numpy as np
lr = 0.01
feature = ["Pclass","Sex","Age","Embarked"]
data = np.array(train[feature].values, dtype = float)
data = np.insert(data,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
data_unnorm = data
data

array([[ 1.,  3.,  0., 22.,  0.],
       [ 1.,  1.,  1., 38.,  1.],
       [ 1.,  3.,  1., 26.,  0.],
       ...,
       [ 1.,  3.,  1., 24.,  0.],
       [ 1.,  1.,  0., 26.,  1.],
       [ 1.,  3.,  0., 32.,  2.]])

In [12]:
data = data/np.max(data, axis=0)
data

array([[1.        , 1.        , 0.        , 0.275     , 0.        ],
       [1.        , 0.33333333, 1.        , 0.475     , 0.5       ],
       [1.        , 1.        , 1.        , 0.325     , 0.        ],
       ...,
       [1.        , 1.        , 1.        , 0.3       , 0.        ],
       [1.        , 0.33333333, 0.        , 0.325     , 0.5       ],
       [1.        , 1.        , 0.        , 0.4       , 1.        ]])

In [13]:
Y = np.array(train[["Survived"]].values, dtype = float)
Y

array([[0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],

In [14]:
w = np.random.rand(len(feature)+1).reshape(-1,1)
w

array([[0.69624051],
       [0.58980955],
       [0.18176198],
       [0.32560925],
       [0.67850464]])

In [15]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [16]:
for epoch in range(1000):
    print(f"epoch : {epoch}")
    for j in range(len(w)):
        sum = 0
        for num in range(len(data)):
            sum += (Y[num][0] - sigmoid(np.dot(w.T,data[num])))*data[num][j]
        print(sum)
        w[j] = w[j] + lr*sum

epoch : 0
[-376.85089829]
[155.74072335]
[147.35652228]
[5.52432957]
[-4.21399833]
epoch : 1
[5.82361573]
[-66.63026955]
[77.35282907]
[11.40553056]
[-0.14205044]
epoch : 2
[23.07138733]
[-58.52738426]
[31.1333971]
[11.86071882]
[1.35714092]
epoch : 3
[28.5002766]
[-49.05354789]
[11.20040359]
[10.16683105]
[1.54030764]
epoch : 4
[28.45381099]
[-41.77107632]
[2.73606224]
[8.06831861]
[1.38952348]
epoch : 5
[27.00248687]
[-36.27162118]
[-0.97646912]
[5.91978736]
[1.1448252]
epoch : 6
[25.10090623]
[-31.78113044]
[-2.5104049]
[3.83474721]
[0.88025263]
epoch : 7
[23.04169375]
[-27.90347515]
[-2.98637291]
[1.88734259]
[0.62945301]
epoch : 8
[20.97619936]
[-24.47145544]
[-2.95164411]
[0.12911361]
[0.40862074]
epoch : 9
[18.99823599]
[-21.41949675]
[-2.68933864]
[-1.41115488]
[0.22389911]
epoch : 10
[17.16426238]
[-18.71864856]
[-2.34745946]
[-2.72527749]
[0.07536264]
epoch : 11
[15.50278203]
[-16.34763389]
[-2.00102867]
[-3.82069559]
[-0.04026607]
epoch : 12
[14.02203951]
[-14.28267608]
[-1.

[0.00956013]
[-0.74825811]
[-0.02140107]
epoch : 104
[0.43293063]
[-0.22419328]
[0.00942909]
[-0.72750489]
[-0.02076513]
epoch : 105
[0.42100256]
[-0.21817871]
[0.00929445]
[-0.70734438]
[-0.02014964]
epoch : 106
[0.40941108]
[-0.21232512]
[0.00915673]
[-0.68775876]
[-0.01955386]
epoch : 107
[0.39814626]
[-0.20662823]
[0.00901641]
[-0.66873081]
[-0.01897707]
epoch : 108
[0.38719849]
[-0.20108387]
[0.0088739]
[-0.65024383]
[-0.01841861]
epoch : 109
[0.37655848]
[-0.19568797]
[0.00872963]
[-0.63228169]
[-0.01787782]
epoch : 110
[0.36621721]
[-0.19043658]
[0.00858395]
[-0.61482876]
[-0.01735409]
epoch : 111
[0.35616595]
[-0.18532586]
[0.0084372]
[-0.59786994]
[-0.0168468]
epoch : 112
[0.34639625]
[-0.18035205]
[0.00828971]
[-0.58139057]
[-0.0163554]
epoch : 113
[0.33689992]
[-0.1755115]
[0.00814176]
[-0.5653765]
[-0.01587933]
epoch : 114
[0.32766903]
[-0.17080067]
[0.00799362]
[-0.54981401]
[-0.01541806]
epoch : 115
[0.31869588]
[-0.16621609]
[0.00784552]
[-0.53468981]
[-0.01497108]
epoch

[0.00081359]
[-0.04273901]
[-0.00113691]
epoch : 208
[0.02489361]
[-0.01322042]
[0.00079213]
[-0.04158918]
[-0.00110619]
epoch : 209
[0.02422415]
[-0.01286541]
[0.00077122]
[-0.04047033]
[-0.0010763]
epoch : 210
[0.02357272]
[-0.01251994]
[0.00075085]
[-0.03938164]
[-0.00104722]
epoch : 211
[0.02293883]
[-0.01218374]
[0.00073101]
[-0.03832229]
[-0.00101894]
epoch : 212
[0.02232202]
[-0.01185657]
[0.00071169]
[-0.03729148]
[-0.00099142]
epoch : 213
[0.02172181]
[-0.01153818]
[0.00069287]
[-0.03628845]
[-0.00096465]
epoch : 214
[0.02113776]
[-0.01122835]
[0.00067454]
[-0.03531244]
[-0.00093861]
epoch : 215
[0.02056944]
[-0.01092683]
[0.00065669]
[-0.03436272]
[-0.00091327]
epoch : 216
[0.02001641]
[-0.01063342]
[0.0006393]
[-0.03343859]
[-0.00088862]
epoch : 217
[0.01947828]
[-0.01034788]
[0.00062237]
[-0.03253934]
[-0.00086464]
epoch : 218
[0.01895462]
[-0.01007001]
[0.00060588]
[-0.03166432]
[-0.00084131]
epoch : 219
[0.01844507]
[-0.0097996]
[0.00058982]
[-0.03081286]
[-0.00081861]
ep

[0.00159051]
[-0.00084588]
[5.15098739e-05]
[-0.00265632]
[-7.03576018e-05]
epoch : 310
[0.00154779]
[-0.00082317]
[5.01282226e-05]
[-0.00258498]
[-6.84676397e-05]
epoch : 311
[0.00150623]
[-0.00080106]
[4.8783593e-05]
[-0.00251557]
[-6.6628466e-05]
epoch : 312
[0.00146578]
[-0.00077955]
[4.74749951e-05]
[-0.00244801]
[-6.48387147e-05]
epoch : 313
[0.00142642]
[-0.00075862]
[4.62014654e-05]
[-0.00238227]
[-6.30970568e-05]
epoch : 314
[0.00138811]
[-0.00073825]
[4.49620658e-05]
[-0.0023183]
[-6.14021989e-05]
epoch : 315
[0.00135084]
[-0.00071843]
[4.37558835e-05]
[-0.00225604]
[-5.97528828e-05]
epoch : 316
[0.00131456]
[-0.00069914]
[4.25820299e-05]
[-0.00219546]
[-5.81478837e-05]
epoch : 317
[0.00127926]
[-0.00068036]
[4.14396399e-05]
[-0.0021365]
[-5.65860101e-05]
epoch : 318
[0.00124491]
[-0.00066209]
[4.03278718e-05]
[-0.00207912]
[-5.50661025e-05]
epoch : 319
[0.00121148]
[-0.00064432]
[3.9245906e-05]
[-0.00202329]
[-5.35870325e-05]
epoch : 320
[0.00117895]
[-0.00062702]
[3.8192945

[0.00011981]
[-6.3726878e-05]
[3.88457662e-06]
[-0.0002001]
[-5.2986137e-06]
epoch : 405
[0.0001166]
[-6.20157151e-05]
[3.78027819e-06]
[-0.00019473]
[-5.1563337e-06]
epoch : 406
[0.00011347]
[-6.03504994e-05]
[3.67877995e-06]
[-0.0001895]
[-5.01787433e-06]
epoch : 407
[0.00011042]
[-5.87299974e-05]
[3.58000664e-06]
[-0.00018441]
[-4.88313304e-06]
epoch : 408
[0.00010746]
[-5.71530083e-05]
[3.48388516e-06]
[-0.00017946]
[-4.75200994e-06]
epoch : 409
[0.00010457]
[-5.56183637e-05]
[3.39034429e-06]
[-0.00017464]
[-4.6244079e-06]
epoch : 410
[0.00010176]
[-5.41249267e-05]
[3.2993148e-06]
[-0.00016995]
[-4.50023234e-06]
epoch : 411
[9.90293124e-05]
[-5.26715907e-05]
[3.21072923e-06]
[-0.00016539]
[-4.37939125e-06]
epoch : 412
[9.63702104e-05]
[-5.12572791e-05]
[3.12452202e-06]
[-0.00016095]
[-4.2617951e-06]
epoch : 413
[9.37825101e-05]
[-4.98809438e-05]
[3.04062928e-06]
[-0.00015662]
[-4.14735673e-06]
epoch : 414
[9.12642942e-05]
[-4.85415652e-05]
[2.95898892e-06]
[-0.00015242]
[-4.0359913

[1.21773662e-05]
[-6.47691697e-06]
[3.948403e-07]
[-2.0337077e-05]
[-5.38512779e-07]
epoch : 489
[1.18503854e-05]
[-6.30300203e-06]
[3.84238339e-07]
[-1.97909954e-05]
[-5.24052858e-07]
epoch : 490
[1.15321845e-05]
[-6.13375693e-06]
[3.73921048e-07]
[-1.9259577e-05]
[-5.09981205e-07]
epoch : 491
[1.12225278e-05]
[-5.96905635e-06]
[3.6388079e-07]
[-1.8742428e-05]
[-4.96287414e-07]
epoch : 492
[1.09211859e-05]
[-5.8087782e-06]
[3.54110116e-07]
[-1.82391652e-05]
[-4.82961306e-07]
epoch : 493
[1.06279355e-05]
[-5.65280381e-06]
[3.44601792e-07]
[-1.77494158e-05]
[-4.69993037e-07]
epoch : 494
[1.03425592e-05]
[-5.50101752e-06]
[3.35348771e-07]
[-1.7272817e-05]
[-4.57372987e-07]
epoch : 495
[1.00648458e-05]
[-5.35330695e-06]
[3.26344216e-07]
[-1.68090155e-05]
[-4.45091801e-07]
epoch : 496
[9.79458945e-06]
[-5.20956261e-06]
[3.17581438e-07]
[-1.63576679e-05]
[-4.33140397e-07]
epoch : 497
[9.53158981e-06]
[-5.06967802e-06]
[3.09053973e-07]
[-1.59184396e-05]
[-4.21509899e-07]
epoch : 498
[9.27565

[4.01301175e-08]
[-2.0669691e-06]
[-5.47319189e-08]
epoch : 573
[1.20442012e-06]
[-6.40609332e-07]
[3.90525849e-08]
[-2.01146786e-06]
[-5.32622679e-08]
epoch : 574
[1.17207966e-06]
[-6.23408018e-07]
[3.80039598e-08]
[-1.95745693e-06]
[-5.18321061e-08]
epoch : 575
[1.14060755e-06]
[-6.06668574e-07]
[3.69834934e-08]
[-1.90489627e-06]
[-5.04403288e-08]
epoch : 576
[1.10998055e-06]
[-5.90378617e-07]
[3.59904462e-08]
[-1.85374694e-06]
[-4.90859332e-08]
epoch : 577
[1.08017587e-06]
[-5.74526054e-07]
[3.50240309e-08]
[-1.80397106e-06]
[-4.77679027e-08]
epoch : 578
[1.05117152e-06]
[-5.59099166e-07]
[3.40835816e-08]
[-1.75553172e-06]
[-4.64852645e-08]
epoch : 579
[1.02294597e-06]
[-5.44086502e-07]
[3.31684e-08]
[-1.70839304e-06]
[-4.52370676e-08]
epoch : 580
[9.95478327e-07]
[-5.29476945e-07]
[3.22777819e-08]
[-1.66252012e-06]
[-4.40223755e-08]
epoch : 581
[9.6874826e-07]
[-5.15259712e-07]
[3.14110553e-08]
[-1.61787896e-06]
[-4.28403169e-08]
epoch : 582
[9.4273589e-07]
[-5.01424201e-07]
[3.056

[1.25789566e-07]
[-6.69052019e-08]
[4.07866141e-09]
[-2.10077607e-07]
[-5.56270546e-09]
epoch : 657
[1.22411939e-07]
[-6.51087085e-08]
[3.96914701e-09]
[-2.04436717e-07]
[-5.4133374e-09]
epoch : 658
[1.19125016e-07]
[-6.3360458e-08]
[3.86257426e-09]
[-1.98947276e-07]
[-5.26798601e-09]
epoch : 659
[1.15926306e-07]
[-6.16591009e-08]
[3.75885667e-09]
[-1.93605245e-07]
[-5.12653114e-09]
epoch : 660
[1.12813534e-07]
[-6.00034791e-08]
[3.65790975e-09]
[-1.88406662e-07]
[-4.98888041e-09]
epoch : 661
[1.09784282e-07]
[-5.83922912e-08]
[3.55969809e-09]
[-1.8334765e-07]
[-4.85491393e-09]
epoch : 662
[1.0683645e-07]
[-5.68243816e-08]
[3.46411644e-09]
[-1.78424498e-07]
[-4.72456238e-09]
epoch : 663
[1.03967717e-07]
[-5.5298561e-08]
[3.37109352e-09]
[-1.73633533e-07]
[-4.5976935e-09]
epoch : 664
[1.01176038e-07]
[-5.38137112e-08]
[3.28057481e-09]
[-1.68971217e-07]
[-4.4742406e-09]
epoch : 665
[9.84593032e-08]
[-5.2368733e-08]
[3.19248317e-09]
[-1.64434076e-07]
[-4.35410472e-09]
epoch : 666
[9.58155

[1.21073583e-08]
[-6.43969388e-09]
[3.92577415e-10]
[-2.02201149e-08]
[-5.35414532e-10]
epoch : 743
[1.17822572e-08]
[-6.26677996e-09]
[3.82028409e-10]
[-1.96771903e-08]
[-5.21045998e-10]
epoch : 744
[1.14658528e-08]
[-6.09847903e-09]
[3.71771947e-10]
[-1.91488126e-08]
[-5.07047737e-10]
epoch : 745
[1.11580096e-08]
[-5.93475565e-09]
[3.6179526e-10]
[-1.86346439e-08]
[-4.93423039e-10]
epoch : 746
[1.08583828e-08]
[-5.77536247e-09]
[3.52071816e-10]
[-1.81342728e-08]
[-4.80177439e-10]
epoch : 747
[1.05668296e-08]
[-5.62029388e-09]
[3.42608608e-10]
[-1.76473379e-08]
[-4.67285724e-10]
epoch : 748
[1.02830972e-08]
[-5.46938828e-09]
[3.33417405e-10]
[-1.71734822e-08]
[-4.54744936e-10]
epoch : 749
[1.0006967e-08]
[-5.32253941e-09]
[3.24466676e-10]
[-1.67123516e-08]
[-4.42531858e-10]
epoch : 750
[9.7382858e-09]
[-5.17959033e-09]
[3.1575409e-10]
[-1.62636019e-08]
[-4.30649169e-10]
epoch : 751
[9.47676937e-09]
[-5.04052514e-09]
[3.07274872e-10]
[-1.58269071e-08]
[-4.19086682e-10]
epoch : 752
[9.2

[-6.72547934e-10]
[4.09799972e-11]
[-2.11178926e-09]
[-5.59207819e-11]
epoch : 826
[1.23051794e-09]
[-6.54511834e-10]
[3.98898692e-11]
[-2.05508928e-09]
[-5.44151113e-11]
epoch : 827
[1.19747412e-09]
[-6.36903405e-10]
[3.88415966e-11]
[-1.99989687e-09]
[-5.29505467e-11]
epoch : 828
[1.16535376e-09]
[-6.19836987e-10]
[3.77616827e-11]
[-1.94620107e-09]
[-5.15376908e-11]
epoch : 829
[1.13404576e-09]
[-6.0318496e-10]
[3.6792791e-11]
[-1.89392874e-09]
[-5.01489544e-11]
epoch : 830
[1.10361112e-09]
[-5.86992427e-10]
[3.57911478e-11]
[-1.84308608e-09]
[-4.88042246e-11]
epoch : 831
[1.07398818e-09]
[-5.71228051e-10]
[3.48252538e-11]
[-1.79359268e-09]
[-4.74891515e-11]
epoch : 832
[1.04511248e-09]
[-5.55880689e-10]
[3.38882256e-11]
[-1.74543828e-09]
[-4.62199168e-11]
epoch : 833
[1.01706765e-09]
[-5.40961345e-10]
[3.29629657e-11]
[-1.69857901e-09]
[-4.49814491e-11]
epoch : 834
[9.89753876e-10]
[-5.26443944e-10]
[3.20922178e-11]
[-1.65297215e-09]
[-4.37778841e-11]
epoch : 835
[9.63151711e-10]
[-

[-2.20550085e-10]
[-5.83712245e-12]
epoch : 909
[1.2851134e-10]
[-6.8355932e-11]
[4.1641135e-12]
[-2.14634269e-10]
[-5.68822767e-12]
epoch : 910
[1.250475e-10]
[-6.65228567e-11]
[4.0580872e-12]
[-2.08860491e-10]
[-5.52735635e-12]
epoch : 911
[1.21713126e-10]
[-6.47279313e-11]
[3.96283006e-12]
[-2.03259819e-10]
[-5.38263878e-12]
epoch : 912
[1.18462573e-10]
[-6.3004324e-11]
[3.84581256e-12]
[-1.97809429e-10]
[-5.23658894e-12]
epoch : 913
[1.15256998e-10]
[-6.12951634e-11]
[3.7265746e-12]
[-1.92497296e-10]
[-5.09509102e-12]
epoch : 914
[1.12147153e-10]
[-5.96536154e-11]
[3.62887498e-12]
[-1.87326293e-10]
[-4.96053199e-12]
epoch : 915
[1.09135673e-10]
[-5.80571563e-11]
[3.534395e-12]
[-1.82300272e-10]
[-4.83185714e-12]
epoch : 916
[1.06207848e-10]
[-5.64785579e-11]
[3.44457796e-12]
[-1.77404098e-10]
[-4.69241312e-12]
epoch : 917
[1.03371367e-10]
[-5.49731927e-11]
[3.3397729e-12]
[-1.72623818e-10]
[-4.57078819e-12]
epoch : 918
[1.006107e-10]
[-5.35261974e-11]
[3.25139915e-12]
[-1.67999545e

[-7.34666494e-12]
[4.47641924e-13]
[-2.3039147e-11]
[-6.11607986e-13]
epoch : 992
[1.34133121e-11]
[-7.14368842e-12]
[4.44422277e-13]
[-2.24104138e-11]
[-5.89292504e-13]
epoch : 993
[1.30560146e-11]
[-6.94597158e-12]
[4.22106794e-13]
[-2.18107615e-11]
[-5.845463e-13]
epoch : 994
[1.26935962e-11]
[-6.77569112e-12]
[4.17887946e-13]
[-2.12165008e-11]
[-5.5958016e-13]
epoch : 995
[1.23975413e-11]
[-6.58809118e-12]
[4.02455846e-13]
[-2.06538953e-11]
[-5.47117907e-13]
epoch : 996
[1.20435051e-11]
[-6.40444642e-12]
[3.91797705e-13]
[-2.01001438e-11]
[-5.34933209e-13]
epoch : 997
[1.171227e-11]
[-6.23504026e-12]
[3.73368003e-13]
[-1.9558917e-11]
[-5.22457078e-13]
epoch : 998
[1.13973414e-11]
[-6.06630024e-12]
[3.96127575e-13]
[-1.90254548e-11]
[-5.02237141e-13]
epoch : 999
[1.11020498e-11]
[-5.90932858e-12]
[3.57602836e-13]
[-1.85271937e-11]
[-4.90718577e-13]


In [17]:
#predicting on train set
train_res = []
for num in range(len(data)):
    if sigmoid(np.dot(w.T,data[num])) >= 0.5:
        train_res.append(1)
    else:
        train_res.append(0)

In [18]:
train_res = np.array(train_res).reshape(-1,1)
train_res

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
    

In [19]:
sum = 0
for i in range(len(train_res)):
    if int(train_res[i][0]) == int(Y[i][0]):
        sum += 1
print(sum/len(train_res))

0.7811447811447811


In [20]:
test.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [21]:
test["Age"] = test["Age"].fillna(test["Age"].mode()[0])
print(pd.unique(test["Embarked"]))
print(test["Embarked"].isna().sum())

['Q' 'S' 'C']
0


In [22]:
test.loc[test["Embarked"] == "S", "Embarked"] = 0
test.loc[test["Embarked"] == "C", "Embarked"] = 1
test.loc[test["Embarked"] == "Q", "Embarked"] = 2
test["Embarked"] = test["Embarked"].fillna(test["Embarked"].mode()[0])
print(pd.unique(test["Sex"]))

['male' 'female']


In [23]:
test.loc[test["Sex"] == "male", "Sex"] = 0
test.loc[test["Sex"] == "female", "Sex"] = 1

In [24]:
X_test = np.array(test[feature].values, dtype = float)
X_test = np.insert(X_test,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
X_test = X_test/np.max(data_unnorm, axis=0)
X_test

array([[1.        , 1.        , 0.        , 0.43125   , 1.        ],
       [1.        , 1.        , 1.        , 0.5875    , 0.        ],
       [1.        , 0.66666667, 0.        , 0.775     , 1.        ],
       ...,
       [1.        , 1.        , 0.        , 0.48125   , 0.        ],
       [1.        , 1.        , 0.        , 0.2625    , 0.        ],
       [1.        , 1.        , 0.        , 0.2625    , 0.5       ]])

In [25]:
test

PassengerId  Pclass                                          Name Sex  \
0            892       3                              Kelly, Mr. James   0   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   1   
2            894       2                     Myles, Mr. Thomas Francis   0   
3            895       3                              Wirz, Mr. Albert   0   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   1   
..           ...     ...                                           ...  ..   
413         1305       3                            Spector, Mr. Woolf   0   
414         1306       1                  Oliva y Ocana, Dona. Fermina   1   
415         1307       3                  Saether, Mr. Simon Sivertsen   0   
416         1308       3                           Ware, Mr. Frederick   0   
417         1309       3                      Peter, Master. Michael J   0   

      Age  SibSp  Parch              Ticket      Fare Cabin  Embarked  
0    34.5      0      0              330911    7.8292   NaN         2  
1    47.0      1      0              363272    7.0000   NaN         0  
2    62.0      0      0              240276    9.6875   NaN         2  
3    27.0      0      0              315154    8.6625   NaN         0  
4    22.0      1      1             3101298   12.2875   NaN         0  
..    ...    ...    ...                 ...       ...   ...       ...  
413  21.0      0      0           A.5. 3236    8.0500   NaN         0  
414  39.0      0      0            PC 17758  108.9000  C105         1  
415  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN         0  
416  21.0      0      0              359309    8.0500   NaN         0  
417  21.0      1      1                2668   22.3583   NaN         1  

[418 rows x 11 columns]

In [26]:
#predicting on test set
test_res = []
for num in range(len(X_test)):
    if sigmoid(np.dot(w.T,X_test[num])) >= 0.5:
        test_res.append(1)
    else:
        test_res.append(0)
test_res = np.array(test_res).reshape(-1,1)
print(test_res)

[[0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]


# T7

In [27]:
df_result = pd.DataFrame()
df_result = test[["PassengerId"]]
df_result["Survived"] = test_res.reshape(-1)
df_result

<ipython-input-27-1fd4da4a8654>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result["Survived"] = test_res.reshape(-1)


PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [28]:
#df_result.to_csv("submission.csv",index=False)

# T8

In [29]:
x1_x2 = []
x1_2 = []
for i in data_unnorm:
    x1_x2.append(i[1]*i[2])
    x1_2.append(i[1]**2)
data_unnorm = np.insert(data_unnorm,1,np.array(x1_x2),axis=1)
data_unnorm = np.insert(data_unnorm,1,np.array(x1_2),axis=1)
data = data_unnorm/np.max(data_unnorm, axis=0)
data

array([[1.        , 1.        , 0.        , ..., 0.        , 0.275     ,
        0.        ],
       [1.        , 0.11111111, 0.33333333, ..., 1.        , 0.475     ,
        0.5       ],
       [1.        , 1.        , 1.        , ..., 1.        , 0.325     ,
        0.        ],
       ...,
       [1.        , 1.        , 1.        , ..., 1.        , 0.3       ,
        0.        ],
       [1.        , 0.11111111, 0.        , ..., 0.        , 0.325     ,
        0.5       ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.4       ,
        1.        ]])

In [30]:
w = np.random.rand(data.shape[1]).reshape(-1,1)
w

array([[0.9707358 ],
       [0.70859483],
       [0.45743741],
       [0.17876587],
       [0.44815546],
       [0.63397592],
       [0.95742981]])

In [31]:
for epoch in range(1000):
    print(f"epoch : {epoch}")
    for j in range(len(w)):
        sum = 0
        for num in range(len(data)):
            sum += (Y[num][0] - sigmoid(np.dot(w.T,data[num])))*data[num][j]
        print(sum)
        w[j] = w[j] + lr*sum

epoch : 0
[-454.55012264]
[100.39539126]
[76.16793259]
[34.83144148]
[99.48071804]
[16.88762748]
[-5.11632196]
epoch : 1
[28.26680053]
[-108.3047036]
[8.3088655]
[14.29144984]
[47.86254754]
[17.25476298]
[-1.24059839]
epoch : 2
[37.43128542]
[-80.24137368]
[-15.32809695]
[6.14035263]
[20.62984555]
[13.89534827]
[-0.18874629]
epoch : 3
[37.08007891]
[-60.99133689]
[-20.19407872]
[4.55074025]
[9.25496166]
[9.23175333]
[-0.24556394]
epoch : 4
[32.90921405]
[-47.41980055]
[-18.95921284]
[4.35789824]
[5.10010384]
[4.42531413]
[-0.58398439]
epoch : 5
[27.57331289]
[-36.76621262]
[-16.11630697]
[4.05861646]
[3.85028655]
[0.16667508]
[-0.89094953]
epoch : 6
[22.38639133]
[-28.16212086]
[-13.29163762]
[3.58178501]
[3.65540564]
[-3.21560206]
[-1.07646458]
epoch : 7
[17.96314636]
[-21.37700581]
[-10.99006551]
[3.08551255]
[3.75520798]
[-5.69804361]
[-1.14762917]
epoch : 8
[14.45429669]
[-16.19362773]
[-9.26491324]
[2.66505194]
[3.87220422]
[-7.41559446]
[-1.13913032]
epoch : 9
[11.77468994]
[-12.

[0.35616045]
[-0.10252011]
[-1.94905587]
[0.23889493]
[1.66151799]
[-1.30859342]
[0.03427015]
epoch : 79
[0.34396677]
[-0.09263747]
[-1.92765894]
[0.22835548]
[1.64444164]
[-1.27152276]
[0.03441317]
epoch : 80
[0.33224777]
[-0.08298241]
[-1.90660384]
[0.21797746]
[1.62760154]
[-1.235618]
[0.03452862]
epoch : 81
[0.32098556]
[-0.07354888]
[-1.88588222]
[0.20775757]
[1.6109935]
[-1.20083865]
[0.03461815]
epoch : 82
[0.31016299]
[-0.06433098]
[-1.86548606]
[0.19769263]
[1.5946134]
[-1.16714584]
[0.03468333]
epoch : 83
[0.29976361]
[-0.05532299]
[-1.84540762]
[0.18777952]
[1.57845721]
[-1.13450217]
[0.03472561]
epoch : 84
[0.28977159]
[-0.04651931]
[-1.82563944]
[0.17801523]
[1.56252097]
[-1.1028717]
[0.03474639]
epoch : 85
[0.28017177]
[-0.03791453]
[-1.80617433]
[0.16839683]
[1.54680082]
[-1.07221989]
[0.03474696]
epoch : 86
[0.27094956]
[-0.02950337]
[-1.78700534]
[0.15892148]
[1.53129295]
[-1.0425135]
[0.03472855]
epoch : 87
[0.26209098]
[-0.02128069]
[-1.76812576]
[0.14958641]
[1.5159

[-0.26538426]
[0.80563873]
[-0.17839145]
[0.01873905]
epoch : 158
[0.07969923]
[0.2817868]
[-0.90941663]
[-0.26897245]
[0.7990523]
[-0.17463383]
[0.01850286]
epoch : 159
[0.07978187]
[0.28382328]
[-0.90179607]
[-0.2725154]
[0.79253477]
[-0.17097493]
[0.01826823]
epoch : 160
[0.07988706]
[0.28582587]
[-0.89425793]
[-0.2760137]
[0.78608522]
[-0.16741196]
[0.01803517]
epoch : 161
[0.08001385]
[0.28779522]
[-0.88680108]
[-0.27946793]
[0.77970276]
[-0.16394221]
[0.0178037]
epoch : 162
[0.0801613]
[0.28973197]
[-0.8794244]
[-0.28287869]
[0.7733865]
[-0.16056307]
[0.01757383]
epoch : 163
[0.08032852]
[0.29163674]
[-0.87212677]
[-0.28624653]
[0.76713556]
[-0.15727199]
[0.01734557]
epoch : 164
[0.08051464]
[0.29351014]
[-0.86490712]
[-0.28957202]
[0.7609491]
[-0.15406651]
[0.01711892]
epoch : 165
[0.08071881]
[0.29535275]
[-0.85776438]
[-0.29285571]
[0.75482627]
[-0.15094422]
[0.01689389]
epoch : 166
[0.08094024]
[0.29716516]
[-0.85069751]
[-0.29609814]
[0.74876624]
[-0.14790281]
[0.01667049]
e

[-0.49022136]
[-0.4480248]
[0.43657189]
[-0.04754998]
[0.00463529]
epoch : 239
[0.11263431]
[0.37424123]
[-0.48674175]
[-0.44928844]
[0.43352729]
[-0.04701609]
[0.00451701]
epoch : 240
[0.11305745]
[0.37478335]
[-0.48329299]
[-0.45053487]
[0.43050908]
[-0.04649326]
[0.00439983]
epoch : 241
[0.11347754]
[0.37531599]
[-0.47987475]
[-0.45176429]
[0.42751695]
[-0.0459812]
[0.00428374]
epoch : 242
[0.11389456]
[0.37583929]
[-0.47648669]
[-0.45297687]
[0.42455065]
[-0.04547965]
[0.00416873]
epoch : 243
[0.11430847]
[0.37635334]
[-0.47312849]
[-0.4541728]
[0.4216099]
[-0.04498835]
[0.00405479]
epoch : 244
[0.11471924]
[0.37685827]
[-0.46979983]
[-0.45535226]
[0.41869444]
[-0.04450704]
[0.00394191]
epoch : 245
[0.11512684]
[0.3773542]
[-0.46650039]
[-0.45651542]
[0.415804]
[-0.04403547]
[0.00383009]
epoch : 246
[0.11553126]
[0.37784122]
[-0.46322987]
[-0.45766246]
[0.41293832]
[-0.0435734]
[0.00371931]
epoch : 247
[0.11593245]
[0.37831945]
[-0.45998794]
[-0.45879355]
[0.41009714]
[-0.0431206]


[0.39490672]
[-0.29114879]
[-0.50631194]
[0.26134698]
[-0.02544171]
[-0.00192294]
epoch : 317
[0.13587042]
[0.39496342]
[-0.28933096]
[-0.50665244]
[0.25973692]
[-0.02530036]
[-0.00197928]
epoch : 318
[0.13604704]
[0.39501609]
[-0.28752729]
[-0.50698517]
[0.25813921]
[-0.02516084]
[-0.00203508]
epoch : 319
[0.13622101]
[0.39506475]
[-0.28573765]
[-0.50731022]
[0.25655375]
[-0.02502312]
[-0.00209034]
epoch : 320
[0.13639232]
[0.39510946]
[-0.28396193]
[-0.50762766]
[0.25498044]
[-0.02488716]
[-0.00214507]
epoch : 321
[0.13656101]
[0.39515025]
[-0.28219998]
[-0.50793756]
[0.25341916]
[-0.02475292]
[-0.00219927]
epoch : 322
[0.13672709]
[0.39518715]
[-0.28045168]
[-0.50823999]
[0.2518698]
[-0.02462038]
[-0.00225295]
epoch : 323
[0.13689057]
[0.39522021]
[-0.27871691]
[-0.50853504]
[0.25033227]
[-0.0244895]
[-0.0023061]
epoch : 324
[0.13705148]
[0.39524947]
[-0.27699555]
[-0.50882275]
[0.24880646]
[-0.02436025]
[-0.00235875]
epoch : 325
[0.13720983]
[0.39527496]
[-0.27528748]
[-0.50910322]

[0.16589363]
[-0.01804082]
[-0.00500241]
epoch : 395
[0.14297809]
[0.38955595]
[-0.18272087]
[-0.51423422]
[0.16498818]
[-0.01797685]
[-0.00502814]
epoch : 396
[0.14299806]
[0.38938918]
[-0.18171266]
[-0.51414243]
[0.16408912]
[-0.01791338]
[-0.00505359]
epoch : 397
[0.1430166]
[0.38922054]
[-0.18071162]
[-0.51404698]
[0.1631964]
[-0.0178504]
[-0.00507876]
epoch : 398
[0.14303374]
[0.38905003]
[-0.1797177]
[-0.5139479]
[0.16230997]
[-0.01778792]
[-0.00510368]
epoch : 399
[0.14304948]
[0.38887769]
[-0.17873084]
[-0.51384523]
[0.16142979]
[-0.01772592]
[-0.00512832]
epoch : 400
[0.14306384]
[0.38870352]
[-0.17775098]
[-0.513739]
[0.1605558]
[-0.0176644]
[-0.0051527]
epoch : 401
[0.14307683]
[0.38852754]
[-0.17677806]
[-0.51362925]
[0.15968795]
[-0.01760335]
[-0.00517682]
epoch : 402
[0.14308846]
[0.38834978]
[-0.17581204]
[-0.51351601]
[0.1588262]
[-0.01754276]
[-0.00520069]
epoch : 403
[0.14309874]
[0.38817025]
[-0.17485285]
[-0.51339932]
[0.15797049]
[-0.01748263]
[-0.00522429]
epoch :

[0.37182247]
[-0.12129207]
[-0.49802266]
[0.11010926]
[-0.01411816]
[-0.00636115]
epoch : 475
[0.14097368]
[0.37155264]
[-0.12070742]
[-0.49772717]
[0.10958598]
[-0.01408066]
[-0.00637096]
epoch : 476
[0.1409124]
[0.37128197]
[-0.12012666]
[-0.49742999]
[0.10906616]
[-0.01404338]
[-0.00638064]
epoch : 477
[0.14085044]
[0.37101048]
[-0.11954975]
[-0.49713113]
[0.10854978]
[-0.01400631]
[-0.00639018]
epoch : 478
[0.14078781]
[0.37073817]
[-0.11897667]
[-0.4968306]
[0.10803681]
[-0.01396945]
[-0.00639958]
epoch : 479
[0.14072451]
[0.37046506]
[-0.11840739]
[-0.49652843]
[0.10752722]
[-0.0139328]
[-0.00640884]
epoch : 480
[0.14066055]
[0.37019114]
[-0.11784188]
[-0.49622462]
[0.10702099]
[-0.01389635]
[-0.00641797]
epoch : 481
[0.14059593]
[0.36991644]
[-0.11728012]
[-0.49591921]
[0.1065181]
[-0.01386012]
[-0.00642697]
epoch : 482
[0.14053066]
[0.36964095]
[-0.11672208]
[-0.4956122]
[0.10601852]
[-0.01382408]
[-0.00643583]
epoch : 483
[0.14046475]
[0.3693647]
[-0.11616772]
[-0.49530361]
[0

[-0.47100963]
[0.07800902]
[-0.01172277]
[-0.00678343]
epoch : 553
[0.13457504]
[0.34856772]
[-0.08511085]
[-0.47062423]
[0.07769262]
[-0.01169775]
[-0.00678519]
epoch : 554
[0.13447665]
[0.34825545]
[-0.08476029]
[-0.47023814]
[0.0773782]
[-0.01167285]
[-0.00678688]
epoch : 555
[0.13437796]
[0.34794289]
[-0.08441192]
[-0.46985134]
[0.07706574]
[-0.01164806]
[-0.0067885]
epoch : 556
[0.13427896]
[0.34763005]
[-0.08406573]
[-0.46946387]
[0.07675523]
[-0.01162339]
[-0.00679005]
epoch : 557
[0.13417967]
[0.34731693]
[-0.08372171]
[-0.46907572]
[0.07644665]
[-0.01159883]
[-0.00679152]
epoch : 558
[0.13408008]
[0.34700353]
[-0.08337983]
[-0.46868691]
[0.07613999]
[-0.01157438]
[-0.00679293]
epoch : 559
[0.1339802]
[0.34668987]
[-0.08304009]
[-0.46829745]
[0.07583524]
[-0.01155005]
[-0.00679426]
epoch : 560
[0.13388003]
[0.34637594]
[-0.08270247]
[-0.46790733]
[0.07553238]
[-0.01152583]
[-0.00679553]
epoch : 561
[0.13377958]
[0.34606174]
[-0.08236695]
[-0.46751658]
[0.07523141]
[-0.01150172]

[0.05814714]
[-0.01005032]
[-0.00673871]
epoch : 632
[0.12609727]
[0.32334653]
[-0.06311614]
[-0.43860945]
[0.05795136]
[-0.01003246]
[-0.00673623]
epoch : 633
[0.12598349]
[0.32302399]
[-0.06289946]
[-0.43819162]
[0.05775672]
[-0.01001468]
[-0.00673371]
epoch : 634
[0.1258696]
[0.32270145]
[-0.06268405]
[-0.43777363]
[0.05756322]
[-0.00999696]
[-0.00673116]
epoch : 635
[0.12575561]
[0.32237892]
[-0.06246991]
[-0.43735548]
[0.05737085]
[-0.0099793]
[-0.00672857]
epoch : 636
[0.12564152]
[0.32205639]
[-0.06225702]
[-0.43693718]
[0.05717961]
[-0.00996172]
[-0.00672594]
epoch : 637
[0.12552734]
[0.32173388]
[-0.06204538]
[-0.43651874]
[0.05698948]
[-0.0099442]
[-0.00672328]
epoch : 638
[0.12541306]
[0.32141138]
[-0.06183498]
[-0.43610016]
[0.05680046]
[-0.00992675]
[-0.00672058]
epoch : 639
[0.12529868]
[0.32108889]
[-0.06162581]
[-0.43568144]
[0.05661255]
[-0.00990937]
[-0.00671785]
epoch : 640
[0.12518421]
[0.32076642]
[-0.06141786]
[-0.43526258]
[0.05642573]
[-0.00989205]
[-0.00671508]

[0.29836884]
[-0.04946218]
[-0.40585232]
[0.04567739]
[-0.00882184]
[-0.00645049]
epoch : 711
[0.11691446]
[0.29805298]
[-0.04932305]
[-0.40543381]
[0.04555221]
[-0.0088083]
[-0.0064459]
epoch : 712
[0.11679712]
[0.29773727]
[-0.04918469]
[-0.40501543]
[0.04542771]
[-0.00879482]
[-0.0064413]
epoch : 713
[0.11667979]
[0.29742172]
[-0.04904707]
[-0.40459716]
[0.04530388]
[-0.00878137]
[-0.00643668]
epoch : 714
[0.11656246]
[0.29710633]
[-0.0489102]
[-0.40417902]
[0.04518072]
[-0.00876796]
[-0.00643204]
epoch : 715
[0.11644514]
[0.29679109]
[-0.04877408]
[-0.403761]
[0.04505822]
[-0.0087546]
[-0.00642739]
epoch : 716
[0.11632782]
[0.29647602]
[-0.04863869]
[-0.40334311]
[0.04493639]
[-0.00874128]
[-0.00642272]
epoch : 717
[0.11621051]
[0.2961611]
[-0.04850403]
[-0.40292535]
[0.04481521]
[-0.008728]
[-0.00641803]
epoch : 718
[0.11609321]
[0.29584635]
[-0.0483701]
[-0.40250772]
[0.04469468]
[-0.00871476]
[-0.00641333]
epoch : 719
[0.11597592]
[0.29553176]
[-0.04823689]
[-0.40209022]
[0.0445

[-0.0078783]
[-0.00605221]
epoch : 789
[0.10783518]
[0.2739819]
[-0.04045665]
[-0.37332197]
[0.03756604]
[-0.00786748]
[-0.00604671]
epoch : 790
[0.10772045]
[0.27368156]
[-0.0403644]
[-0.372919]
[0.03748283]
[-0.00785669]
[-0.0060412]
epoch : 791
[0.10760579]
[0.27338145]
[-0.04027259]
[-0.3725163]
[0.03740003]
[-0.00784592]
[-0.00603569]
epoch : 792
[0.10749118]
[0.27308158]
[-0.04018124]
[-0.37211385]
[0.03731762]
[-0.00783519]
[-0.00603017]
epoch : 793
[0.10737664]
[0.27278193]
[-0.04009033]
[-0.37171167]
[0.03723562]
[-0.00782448]
[-0.00602465]
epoch : 794
[0.10726215]
[0.27248252]
[-0.03999987]
[-0.37130976]
[0.03715402]
[-0.0078138]
[-0.00601912]
epoch : 795
[0.10714772]
[0.27218334]
[-0.03990985]
[-0.37090811]
[0.03707281]
[-0.00780315]
[-0.00601358]
epoch : 796
[0.10703336]
[0.27188439]
[-0.03982027]
[-0.37050672]
[0.03699199]
[-0.00779252]
[-0.00600804]
epoch : 797
[0.10691905]
[0.27158568]
[-0.03973113]
[-0.37010561]
[0.03691156]
[-0.00778192]
[-0.00600249]
epoch : 798
[0.10

[0.09909286]
[0.25128527]
[-0.034427]
[-0.34275196]
[0.0321193]
[-0.00709962]
[-0.00560415]
epoch : 868
[0.09898384]
[0.25100429]
[-0.03436273]
[-0.34237222]
[0.03206113]
[-0.00709063]
[-0.00559838]
epoch : 869
[0.0988749]
[0.25072358]
[-0.03429873]
[-0.34199281]
[0.0320032]
[-0.00708166]
[-0.00559261]
epoch : 870
[0.09876606]
[0.25044313]
[-0.034235]
[-0.34161373]
[0.03194551]
[-0.00707271]
[-0.00558684]
epoch : 871
[0.09865729]
[0.25016294]
[-0.03417155]
[-0.34123498]
[0.03188808]
[-0.00706378]
[-0.00558107]
epoch : 872
[0.09854861]
[0.24988302]
[-0.03410837]
[-0.34085655]
[0.03183088]
[-0.00705487]
[-0.0055753]
epoch : 873
[0.09844002]
[0.24960336]
[-0.03404546]
[-0.34047845]
[0.03177393]
[-0.00704597]
[-0.00556953]
epoch : 874
[0.09833151]
[0.24932395]
[-0.03398282]
[-0.34010068]
[0.03171721]
[-0.0070371]
[-0.00556376]
epoch : 875
[0.09822309]
[0.24904482]
[-0.03392045]
[-0.33972324]
[0.03166074]
[-0.00702824]
[-0.00555799]
epoch : 876
[0.09811476]
[0.24876594]
[-0.03385834]
[-0.33

[-0.00645776]
[-0.00516167]
epoch : 945
[0.09085811]
[0.23016588]
[-0.0301298]
[-0.31414244]
[0.02822185]
[-0.00645003]
[-0.00515599]
epoch : 946
[0.09075621]
[0.22990568]
[-0.03008275]
[-0.31378923]
[0.02817907]
[-0.00644231]
[-0.00515031]
epoch : 947
[0.09065442]
[0.22964576]
[-0.03003588]
[-0.31343637]
[0.02813644]
[-0.0064346]
[-0.00514463]
epoch : 948
[0.09055271]
[0.2293861]
[-0.02998917]
[-0.31308386]
[0.02809397]
[-0.00642691]
[-0.00513895]
epoch : 949
[0.09045111]
[0.22912671]
[-0.02994263]
[-0.31273169]
[0.02805164]
[-0.00641923]
[-0.00513328]
epoch : 950
[0.0903496]
[0.22886759]
[-0.02989627]
[-0.31237988]
[0.02800947]
[-0.00641156]
[-0.00512761]
epoch : 951
[0.09024818]
[0.22860874]
[-0.02985007]
[-0.31202841]
[0.02796745]
[-0.00640391]
[-0.00512194]
epoch : 952
[0.09014687]
[0.22835015]
[-0.02980404]
[-0.3116773]
[0.02792558]
[-0.00639627]
[-0.00511628]
epoch : 953
[0.09004564]
[0.22809184]
[-0.02975817]
[-0.31132653]
[0.02788385]
[-0.00638865]
[-0.00511062]
epoch : 954
[0

In [32]:
#predicting on train set
train_res = []
for num in range(len(data)):
    if sigmoid(np.dot(w.T,data[num])) >= 0.5:
        train_res.append(1)
    else:
        train_res.append(0)
train_res = np.array(train_res).reshape(-1,1)
sum = 0
for i in range(len(train_res)):
    if int(train_res[i][0]) == int(Y[i][0]):
        sum += 1
print(f"accuracy : {sum/len(train_res)}")
# a bit better than before

accuracy : 0.8013468013468014


In [33]:
feature = ["Pclass","Sex","Age","Embarked"]
X_test = np.array(test[feature].values, dtype = float)
X_test = np.insert(X_test,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
X_test

array([[ 1. ,  3. ,  0. , 34.5,  2. ],
       [ 1. ,  3. ,  1. , 47. ,  0. ],
       [ 1. ,  2. ,  0. , 62. ,  2. ],
       ...,
       [ 1. ,  3. ,  0. , 38.5,  0. ],
       [ 1. ,  3. ,  0. , 21. ,  0. ],
       [ 1. ,  3. ,  0. , 21. ,  1. ]])

In [34]:
x1_x2 = []
x1_2 = []
for i in X_test:
    x1_x2.append(i[1]*i[2])
    x1_2.append(i[1]**2)
X_test = np.insert(X_test,1,np.array(x1_x2),axis=1)
X_test = np.insert(X_test,1,np.array(x1_2),axis=1)
X_test = X_test/np.max(data_unnorm, axis=0)
X_test

array([[1.        , 1.        , 0.        , ..., 0.        , 0.43125   ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 0.5875    ,
        0.        ],
       [1.        , 0.44444444, 0.        , ..., 0.        , 0.775     ,
        1.        ],
       ...,
       [1.        , 1.        , 0.        , ..., 0.        , 0.48125   ,
        0.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.2625    ,
        0.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.2625    ,
        0.5       ]])

In [35]:
#predicting on test set
test_res = []
for num in range(len(X_test)):
    if sigmoid(np.dot(w.T,X_test[num])) >= 0.5:
        test_res.append(1)
    else:
        test_res.append(0)
test_res = np.array(test_res).reshape(-1,1)
print(test_res)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]


In [36]:
df_result = pd.DataFrame()
df_result = test[["PassengerId"]]
df_result["Survived"] = test_res.reshape(-1)
df_result

<ipython-input-36-1fd4da4a8654>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result["Survived"] = test_res.reshape(-1)


PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [37]:
df_result.to_csv("submission2.csv",index=False)

In [38]:
"""
after adding to kaggle. as you can see from the picture T8, 
the model doesn't overfitting to train set as my assumption (before fitting) 
and model a bit better accuracy than T6
"""

"\nafter adding to kaggle. as you can see from the picture T8, \nthe model doesn't overfitting to train set as my assumption (before fitting) \nand model a bit better accuracy than T6\n"

# T9

In [39]:
import numpy as np
lr = 0.01
feature = ["Sex","Age"]
data = np.array(train[feature].values, dtype = float)
data = np.insert(data,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
data_unnorm = data
data = data/np.max(data, axis=0)
w = np.random.rand(len(feature)+1).reshape(-1,1)
data


array([[1.   , 0.   , 0.275],
       [1.   , 1.   , 0.475],
       [1.   , 1.   , 0.325],
       ...,
       [1.   , 1.   , 0.3  ],
       [1.   , 0.   , 0.325],
       [1.   , 0.   , 0.4  ]])

In [40]:
for epoch in range(1000):
    print(f"epoch : {epoch}")
    for j in range(len(w)):
        sum = 0
        for num in range(len(data)):
            sum += (Y[num][0] - sigmoid(np.dot(w.T,data[num])))*data[num][j]
        print(sum)
        w[j] = w[j] + lr*sum

epoch : 0
[-200.74133952]
[174.44509302]
[19.43710809]
epoch : 1
[56.46492577]
[10.14685905]
[-22.19365704]
epoch : 2
[-32.14597308]
[30.1880152]
[-3.35574848]
epoch : 3
[3.72072592]
[7.95584603]
[-6.28918029]
epoch : 4
[-3.6025801]
[6.52857187]
[-4.1134956]
epoch : 5
[0.15455695]
[3.22204825]
[-3.87696237]
epoch : 6
[0.04625773]
[2.01407842]
[-3.3977591]
epoch : 7
[0.57717694]
[1.13046878]
[-3.14157798]
epoch : 8
[0.70918629]
[0.65476403]
[-2.92147888]
epoch : 9
[0.81375084]
[0.36038171]
[-2.75000529]
epoch : 10
[0.84856966]
[0.18868856]
[-2.60287134]
epoch : 11
[0.85653581]
[0.08642012]
[-2.47387492]
epoch : 12
[0.84540579]
[0.02676623]
[-2.35710703]
epoch : 13
[0.82439725]
[-0.00758704]
[-2.24950522]
epoch : 14
[0.79783603]
[-0.0267232]
[-2.14901481]
epoch : 15
[0.76860853]
[-0.03679858]
[-2.05436568]
epoch : 16
[0.73835028]
[-0.04150136]
[-1.96471568]
epoch : 17
[0.70804253]
[-0.04305815]
[-1.87949481]
epoch : 18
[0.67824673]
[-0.04280623]
[-1.79829663]
epoch : 19
[0.64927831]
[-0.

[0.00147386]
[-4.45895771e-05]
[-0.00398728]
epoch : 160
[0.00141151]
[-4.26978902e-05]
[-0.00381861]
epoch : 161
[0.00135179]
[-4.08866808e-05]
[-0.00365707]
epoch : 162
[0.00129461]
[-3.91525068e-05]
[-0.00350237]
epoch : 163
[0.00123984]
[-3.74920747e-05]
[-0.00335422]
epoch : 164
[0.00118739]
[-3.59022333e-05]
[-0.00321233]
epoch : 165
[0.00113716]
[-3.43799672e-05]
[-0.00307644]
epoch : 166
[0.00108906]
[-3.29223911e-05]
[-0.0029463]
epoch : 167
[0.00104299]
[-3.15267439e-05]
[-0.00282167]
epoch : 168
[0.00099887]
[-3.01903833e-05]
[-0.00270231]
epoch : 169
[0.00095661]
[-2.89107809e-05]
[-0.002588]
epoch : 170
[0.00091614]
[-2.76855166e-05]
[-0.00247852]
epoch : 171
[0.00087739]
[-2.65122745e-05]
[-0.00237368]
epoch : 172
[0.00084027]
[-2.53888381e-05]
[-0.00227327]
epoch : 173
[0.00080473]
[-2.43130858e-05]
[-0.00217711]
epoch : 174
[0.00077069]
[-2.32829871e-05]
[-0.00208502]
epoch : 175
[0.00073808]
[-2.22965986e-05]
[-0.00199682]
epoch : 176
[0.00070686]
[-2.135206e-05]
[-0.0

[3.95227361e-06]
[-1.19216208e-07]
[-1.06927963e-05]
epoch : 297
[3.78509196e-06]
[-1.1417332e-07]
[-1.02404898e-05]
epoch : 298
[3.62498216e-06]
[-1.09343749e-07]
[-9.80731593e-06]
epoch : 299
[3.47164493e-06]
[-1.04718448e-07]
[-9.39246534e-06]
epoch : 300
[3.32479398e-06]
[-1.00288829e-07]
[-8.995163e-06]
epoch : 301
[3.1841548e-06]
[-9.6046567e-08]
[-8.61466661e-06]
epoch : 302
[3.04946465e-06]
[-9.19837564e-08]
[-8.25026524e-06]
epoch : 303
[2.92047196e-06]
[-8.80928234e-08]
[-7.90127809e-06]
epoch : 304
[2.79693567e-06]
[-8.4366456e-08]
[-7.56705315e-06]
epoch : 305
[2.67862496e-06]
[-8.07977245e-08]
[-7.24696595e-06]
epoch : 306
[2.56531882e-06]
[-7.73799638e-08]
[-6.94041848e-06]
epoch : 307
[2.45680552e-06]
[-7.41067542e-08]
[-6.646838e-06]
epoch : 308
[2.35288239e-06]
[-7.09720164e-08]
[-6.36567602e-06]
epoch : 309
[2.25335513e-06]
[-6.79698452e-08]
[-6.0964072e-06]
epoch : 310
[2.15803803e-06]
[-6.50947445e-08]
[-5.83852853e-06]
epoch : 311
[2.06675273e-06]
[-6.23412049e-08]

[1.25997457e-08]
[-3.800672e-10]
[-3.40883839e-08]
epoch : 430
[1.20667961e-08]
[-3.63990171e-10]
[-3.26464584e-08]
epoch : 431
[1.15563795e-08]
[-3.48602369e-10]
[-3.12654993e-08]
epoch : 432
[1.10675239e-08]
[-3.33845729e-10]
[-2.99429609e-08]
epoch : 433
[1.05993847e-08]
[-3.19712923e-10]
[-2.86763875e-08]
epoch : 434
[1.01509888e-08]
[-3.06191406e-10]
[-2.74633519e-08]
epoch : 435
[9.72162806e-09]
[-2.93220115e-10]
[-2.63016644e-08]
epoch : 436
[9.31040098e-09]
[-2.80842238e-10]
[-2.51890873e-08]
epoch : 437
[8.91655261e-09]
[-2.68941536e-10]
[-2.41235856e-08]
epoch : 438
[8.53941348e-09]
[-2.57584731e-10]
[-2.31031853e-08]
epoch : 439
[8.17815257e-09]
[-2.46686227e-10]
[-2.21258881e-08]
epoch : 440
[7.83227408e-09]
[-2.36242692e-10]
[-2.11899722e-08]
epoch : 441
[7.50093065e-09]
[-2.2626101e-10]
[-2.02936264e-08]
epoch : 442
[7.18362658e-09]
[-2.16683449e-10]
[-1.94352092e-08]
epoch : 443
[6.87978946e-09]
[-2.07526107e-10]
[-1.86130956e-08]
epoch : 444
[6.58875549e-09]
[-1.9873991

[-1.51489932e-12]
[-1.34899258e-10]
epoch : 558
[4.77282103e-11]
[-1.42852397e-12]
[-1.2916776e-10]
epoch : 559
[4.57462679e-11]
[-1.39899203e-12]
[-1.23714566e-10]
epoch : 560
[4.38258874e-11]
[-1.32271971e-12]
[-1.18487067e-10]
epoch : 561
[4.19212443e-11]
[-1.25910393e-12]
[-1.13474743e-10]
epoch : 562
[4.01640665e-11]
[-1.22712951e-12]
[-1.08662968e-10]
epoch : 563
[3.84564602e-11]
[-1.1389778e-12]
[-1.04071501e-10]
epoch : 564
[3.68642616e-11]
[-1.10378373e-12]
[-9.9671868e-11]
epoch : 565
[3.52404494e-11]
[-1.02873265e-12]
[-9.54505225e-11]
epoch : 566
[3.38193362e-11]
[-1.02606812e-12]
[-9.14209958e-11]
epoch : 567
[3.2348374e-11]
[-9.83546578e-13]
[-8.75500367e-11]
epoch : 568
[3.09938464e-11]
[-9.34252675e-13]
[-8.3856061e-11]
epoch : 569
[2.96820069e-11]
[-8.95283847e-13]
[-8.03150324e-11]
epoch : 570
[2.84065271e-11]
[-8.5975671e-13]
[-7.68951292e-11]
epoch : 571
[2.72400158e-11]
[-8.45545856e-13]
[-7.36471439e-11]
epoch : 572
[2.60572675e-11]
[-7.91811061e-13]
[-7.05381586e

[-7.43849426e-15]
[-4.1178172e-13]
epoch : 692
[1.30645494e-13]
[-1.05471187e-14]
[-3.90298904e-13]
epoch : 693
[1.41220369e-13]
[-8.43769499e-15]
[-3.67414432e-13]
epoch : 694
[1.3236634e-13]
[-5.77315973e-15]
[-3.52273766e-13]
epoch : 695
[1.28813626e-13]
[-1.33226763e-14]
[-3.42254003e-13]
epoch : 696
[1.17822418e-13]
[-9.1038288e-15]
[-3.234496e-13]
epoch : 697
[1.13076215e-13]
[-1.93178806e-14]
[-3.13138404e-13]
epoch : 698
[1.21097576e-13]
[-1.37667655e-14]
[-2.99565928e-13]
epoch : 699
[1.06775699e-13]
[-1.67643677e-14]
[-2.87686541e-13]
epoch : 700
[9.65616476e-14]
[-1.42108547e-14]
[-2.69992362e-13]
epoch : 701
[1.14908083e-13]
[-2.49800181e-14]
[-2.50396925e-13]
epoch : 702
[1.03361764e-13]
[-1.82076576e-14]
[-2.58390531e-13]
epoch : 703
[7.53563878e-14]
[9.99200722e-16]
[-2.32314168e-13]
epoch : 704
[9.25093335e-14]
[-3.66373598e-15]
[-2.28012054e-13]
epoch : 705
[8.18511925e-14]
[-1.31006317e-14]
[-2.29760655e-13]
epoch : 706
[7.56339436e-14]
[-4.3298698e-15]
[-2.09818274e-

[-2.44249065e-15]
[-9.52016244e-15]
epoch : 827
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 828
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 829
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 830
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 831
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 832
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 833
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 834
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 835
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 836
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 837
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 838
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 839
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 840
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 841
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-1

[-9.52016244e-15]
epoch : 961
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 962
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 963
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 964
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 965
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 966
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 967
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 968
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 969
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 970
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 971
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 972
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 973
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 974
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 975
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 976
[2.

In [41]:
w

array([[-1.37227573],
       [ 2.50861377],
       [-0.23307829]])

In [42]:
#predicting on train set
train_res = []
for num in range(len(data)):
    if sigmoid(np.dot(data[num],w)) >= 0.5:
        train_res.append(1)
    else:
        train_res.append(0)
train_res = np.array(train_res).reshape(-1,1)
sum = 0
for i in range(len(train_res)):
    if int(train_res[i][0]) == int(Y[i][0]):
        sum += 1
print(sum/len(train_res))

0.7867564534231201


In [43]:
X_test = np.array(test[feature].values, dtype = float)
X_test = np.insert(X_test,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
X_test = X_test/np.max(data_unnorm, axis=0)
X_test

array([[1.     , 0.     , 0.43125],
       [1.     , 1.     , 0.5875 ],
       [1.     , 0.     , 0.775  ],
       ...,
       [1.     , 0.     , 0.48125],
       [1.     , 0.     , 0.2625 ],
       [1.     , 0.     , 0.2625 ]])

In [44]:
#predicting on test set
test_res = []
for num in range(len(X_test)):
    if sigmoid(np.dot(w.T,data[num])) >= 0.5:
        test_res.append(1)
    else:
        test_res.append(0)
test_res = np.array(test_res).reshape(-1,1)
print(test_res)

[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]


In [45]:
df_result = pd.DataFrame()
df_result = test[["PassengerId"]]
df_result["Survived"] = test_res.reshape(-1)
df_result

<ipython-input-45-1fd4da4a8654>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result["Survived"] = test_res.reshape(-1)


PassengerId  Survived
0            892         0
1            893         1
2            894         1
3            895         1
4            896         0
..           ...       ...
413         1305         0
414         1306         0
415         1307         1
416         1308         1
417         1309         1

[418 rows x 2 columns]

In [46]:
#df_result.to_csv("submission3.csv",index=False)

In [47]:
"""
after adding to kaggle. as you can see from the picture T9, the model accuracy can perform a bit better than T7.
It can be described that the more feature doesn't mean the more accuracy of model
"""

"\nafter adding to kaggle. as you can see from the picture T9, the model accuracy can perform a bit better than T7.\nIt can be described that the more feature doesn't mean the more accuracy of model\n"

# OT2

In [48]:
import numpy as np
lr = 0.001
feature = ["Sex","Age"]
data = np.array(train[feature].values, dtype = float)
data = np.insert(data,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
data = data/np.max(data, axis=0)
w = np.random.rand(len(feature)+1).reshape(-1,1)
data

array([[1.   , 0.   , 0.275],
       [1.   , 1.   , 0.475],
       [1.   , 1.   , 0.325],
       ...,
       [1.   , 1.   , 0.3  ],
       [1.   , 0.   , 0.325],
       [1.   , 0.   , 0.4  ]])

In [49]:
for epoch in range(1000):
    print(f"epoch : {epoch}")
    for j in range(len(w)):
        sum = 0
        for num in range(len(data)):
            sum += (Y[num][0] - np.dot(w.T,data[num]))*data[num][j]
        print(sum)
        w[j] = w[j] + lr*sum

epoch : 0
[-785.37410642]
[-96.15678835]
[-22.92649882]
epoch : 1
[-48.11814516]
[-48.40189702]
[0.7210011]
epoch : 2
[9.7239208]
[-36.33414158]
[1.41465464]
epoch : 3
[12.01873476]
[-28.85043652]
[0.48199621]
epoch : 4
[10.21572501]
[-23.05069865]
[-0.36887654]
epoch : 5
[8.46879687]
[-18.43252092]
[-1.04068283]
epoch : 6
[7.04201889]
[-14.74457624]
[-1.56045415]
epoch : 7
[5.89385831]
[-11.79852122]
[-1.95842973]
epoch : 8
[4.97026928]
[-9.44494709]
[-2.25946814]
epoch : 9
[4.22635557]
[-7.56460275]
[-2.48347387]
epoch : 10
[3.62611155]
[-6.0622469]
[-2.64634049]
epoch : 11
[3.14076361]
[-4.86180887]
[-2.7607537]
epoch : 12
[2.74732539]
[-3.90252943]
[-2.83683685]
epoch : 13
[2.42743384]
[-3.13587879]
[-2.88266689]
epoch : 14
[2.16641886]
[-2.52309508]
[-2.90468647]
epoch : 15
[1.95255999]
[-2.03321823]
[-2.90803309]
epoch : 16
[1.77649282]
[-1.64151961]
[-2.89680202]
epoch : 17
[1.63073481]
[-1.32824779]
[-2.87425627]
epoch : 18
[1.50930657]
[-1.07762668]
[-2.84299427]
epoch : 19
[1

[0.03987163]
[-0.00322565]
[-0.10551128]
epoch : 159
[0.03892882]
[-0.00314937]
[-0.10301635]
epoch : 160
[0.0380083]
[-0.0030749]
[-0.10058041]
epoch : 161
[0.03710955]
[-0.00300219]
[-0.09820208]
epoch : 162
[0.03623206]
[-0.0029312]
[-0.09587998]
epoch : 163
[0.03537531]
[-0.00286189]
[-0.0936128]
epoch : 164
[0.03453882]
[-0.00279422]
[-0.09139922]
epoch : 165
[0.03372212]
[-0.00272815]
[-0.08923799]
epoch : 166
[0.03292472]
[-0.00266364]
[-0.08712786]
epoch : 167
[0.03214618]
[-0.00260065]
[-0.08506762]
epoch : 168
[0.03138605]
[-0.00253916]
[-0.0830561]
epoch : 169
[0.03064389]
[-0.00247912]
[-0.08109215]
epoch : 170
[0.02991928]
[-0.0024205]
[-0.07917464]
epoch : 171
[0.02921181]
[-0.00236326]
[-0.07730247]
epoch : 172
[0.02852106]
[-0.00230738]
[-0.07547457]
epoch : 173
[0.02784665]
[-0.00225282]
[-0.07368989]
epoch : 174
[0.02718819]
[-0.00219955]
[-0.07194741]
epoch : 175
[0.02654529]
[-0.00214754]
[-0.07024614]
epoch : 176
[0.0259176]
[-0.00209676]
[-0.06858509]
epoch : 177


[0.00084612]
[-6.84521493e-05]
[-0.00223908]
epoch : 320
[0.00082612]
[-6.68335233e-05]
[-0.00218613]
epoch : 321
[0.00080658]
[-6.52531714e-05]
[-0.00213444]
epoch : 322
[0.00078751]
[-6.37101888e-05]
[-0.00208397]
epoch : 323
[0.00076889]
[-6.22036916e-05]
[-0.00203469]
epoch : 324
[0.00075071]
[-6.07328172e-05]
[-0.00198658]
epoch : 325
[0.00073296]
[-5.92967233e-05]
[-0.0019396]
epoch : 326
[0.00071562]
[-5.78945873e-05]
[-0.00189374]
epoch : 327
[0.0006987]
[-5.65256064e-05]
[-0.00184896]
epoch : 328
[0.00068218]
[-5.51889966e-05]
[-0.00180524]
epoch : 329
[0.00066605]
[-5.38839924e-05]
[-0.00176255]
epoch : 330
[0.0006503]
[-5.26098464e-05]
[-0.00172087]
epoch : 331
[0.00063492]
[-5.1365829e-05]
[-0.00168018]
epoch : 332
[0.00061991]
[-5.01512277e-05]
[-0.00164045]
epoch : 333
[0.00060525]
[-4.8965347e-05]
[-0.00160166]
epoch : 334
[0.00059094]
[-4.78075078e-05]
[-0.00156379]
epoch : 335
[0.00057697]
[-4.66770469e-05]
[-0.00152681]
epoch : 336
[0.00056332]
[-4.55733171e-05]
[-0.0

[-2.23473676e-06]
[-7.30984674e-05]
epoch : 463
[2.6969978e-05]
[-2.18189397e-06]
[-7.13699741e-05]
epoch : 464
[2.63322434e-05]
[-2.1303007e-06]
[-6.96823529e-05]
epoch : 465
[2.57095886e-05]
[-2.0799274e-06]
[-6.80346374e-05]
epoch : 466
[2.51016573e-05]
[-2.03074522e-06]
[-6.64258839e-05]
epoch : 467
[2.4508101e-05]
[-1.982726e-06]
[-6.48551712e-05]
epoch : 468
[2.39285803e-05]
[-1.93584232e-06]
[-6.33215997e-05]
epoch : 469
[2.33627628e-05]
[-1.8900672e-06]
[-6.18242911e-05]
epoch : 470
[2.28103246e-05]
[-1.84537448e-06]
[-6.03623881e-05]
epoch : 471
[2.22709496e-05]
[-1.80173858e-06]
[-5.89350533e-05]
epoch : 472
[2.17443285e-05]
[-1.75913452e-06]
[-5.75414695e-05]
epoch : 473
[2.12301601e-05]
[-1.71753785e-06]
[-5.61808384e-05]
epoch : 474
[2.07281498e-05]
[-1.67692479e-06]
[-5.4852381e-05]
epoch : 475
[2.02380099e-05]
[-1.63727206e-06]
[-5.35553364e-05]
epoch : 476
[1.97594601e-05]
[-1.59855697e-06]
[-5.22889619e-05]
epoch : 477
[1.9292226e-05]
[-1.56075733e-06]
[-5.10525321e-05

[-3.25726487e-06]
epoch : 593
[1.20178119e-06]
[-9.72251144e-08]
[-3.18024328e-06]
epoch : 594
[1.17336374e-06]
[-9.49261273e-08]
[-3.10504294e-06]
epoch : 595
[1.14561827e-06]
[-9.26814735e-08]
[-3.03162081e-06]
epoch : 596
[1.11852888e-06]
[-9.04899325e-08]
[-2.95993481e-06]
epoch : 597
[1.09208004e-06]
[-8.83502007e-08]
[-2.88994392e-06]
epoch : 598
[1.06625659e-06]
[-8.62610328e-08]
[-2.82160802e-06]
epoch : 599
[1.04104381e-06]
[-8.42213282e-08]
[-2.75488802e-06]
epoch : 600
[1.01642717e-06]
[-8.22298252e-08]
[-2.68974567e-06]
epoch : 601
[9.92392639e-07]
[-8.02854243e-08]
[-2.62614369e-06]
epoch : 602
[9.68926453e-07]
[-7.83869825e-08]
[-2.56404566e-06]
epoch : 603
[9.46015106e-07]
[-7.65334336e-08]
[-2.50341598e-06]
epoch : 604
[9.23645545e-07]
[-7.47237054e-08]
[-2.44421996e-06]
epoch : 605
[9.01804957e-07]
[-7.29568037e-08]
[-2.38642373e-06]
epoch : 606
[8.80480748e-07]
[-7.12316568e-08]
[-2.32999411e-06]
epoch : 607
[8.59660853e-07]
[-6.95472944e-08]
[-2.27489884e-06]
epoch :

[-1.3836059e-07]
epoch : 725
[5.10487182e-08]
[-4.12988632e-09]
[-1.35088894e-07]
epoch : 726
[4.98416063e-08]
[-4.03221634e-09]
[-1.31894592e-07]
epoch : 727
[4.86630425e-08]
[-3.93687216e-09]
[-1.28775789e-07]
epoch : 728
[4.75123457e-08]
[-3.8437874e-09]
[-1.25730738e-07]
epoch : 729
[4.63888762e-08]
[-3.75288889e-09]
[-1.22757706e-07]
epoch : 730
[4.52919805e-08]
[-3.6641632e-09]
[-1.19854973e-07]
epoch : 731
[4.42209515e-08]
[-3.5775064e-09]
[-1.17020859e-07]
epoch : 732
[4.31753053e-08]
[-3.49292151e-09]
[-1.14253776e-07]
epoch : 733
[4.21543909e-08]
[-3.41033934e-09]
[-1.11552109e-07]
epoch : 734
[4.11575979e-08]
[-3.32968275e-09]
[-1.0891434e-07]
epoch : 735
[4.01844193e-08]
[-3.25096305e-09]
[-1.06338953e-07]
epoch : 736
[3.92341852e-08]
[-3.17408422e-09]
[-1.03824436e-07]
epoch : 737
[3.83064746e-08]
[-3.0990116e-09]
[-1.01369401e-07]
epoch : 738
[3.74006266e-08]
[-3.02574543e-09]
[-9.8972414e-08]
epoch : 739
[3.65162592e-08]
[-2.9542172e-09]
[-9.66320999e-08]
epoch : 740
[3.

[-1.79660398e-10]
[-5.87723473e-09]
epoch : 857
[2.16839008e-09]
[-1.7541224e-10]
[-5.73824847e-09]
epoch : 858
[2.11717086e-09]
[-1.71268888e-10]
[-5.60255302e-09]
epoch : 859
[2.06711251e-09]
[-1.6722379e-10]
[-5.47009825e-09]
epoch : 860
[2.01816003e-09]
[-1.63262515e-10]
[-5.34072059e-09]
epoch : 861
[1.9704966e-09]
[-1.59395053e-10]
[-5.2144464e-09]
epoch : 862
[1.92388835e-09]
[-1.55622959e-10]
[-5.0911514e-09]
epoch : 863
[1.87840818e-09]
[-1.51935575e-10]
[-4.9707535e-09]
epoch : 864
[1.83398746e-09]
[-1.48342783e-10]
[-4.85322371e-09]
epoch : 865
[1.79059112e-09]
[-1.44834478e-10]
[-4.73845362e-09]
epoch : 866
[1.74828974e-09]
[-1.41425649e-10]
[-4.62642429e-09]
epoch : 867
[1.7069538e-09]
[-1.38071998e-10]
[-4.51701393e-09]
epoch : 868
[1.66658004e-09]
[-1.34798617e-10]
[-4.41021394e-09]
epoch : 869
[1.62714861e-09]
[-1.31602618e-10]
[-4.30592327e-09]
epoch : 870
[1.58866148e-09]
[-1.28525413e-10]
[-4.20410097e-09]
epoch : 871
[1.55111424e-09]
[-1.25481736e-10]
[-4.10470387e-

[-7.10953518e-12]
[-2.32365266e-10]
epoch : 992
[8.57293958e-11]
[-6.93856084e-12]
[-2.2686443e-10]
epoch : 993
[8.36529734e-11]
[-6.77546907e-12]
[-2.2149188e-10]
epoch : 994
[8.17473311e-11]
[-6.6192607e-12]
[-2.16257706e-10]
epoch : 995
[7.97870936e-11]
[-6.45583587e-12]
[-2.11136275e-10]
epoch : 996
[7.79055986e-11]
[-6.3081762e-12]
[-2.0615272e-10]
epoch : 997
[7.6070622e-11]
[-6.15441031e-12]
[-2.01292941e-10]
epoch : 998
[7.4253409e-11]
[-6.01807493e-12]
[-1.96509448e-10]
epoch : 999
[7.24867388e-11]
[-5.87796478e-12]
[-1.91878596e-10]


In [50]:
w

array([[ 0.20301973],
       [ 0.55215353],
       [-0.03855485]])

# OT3

In [51]:
XT_X_INV = np.linalg.inv(np.dot(data.T,data))
XT_Y = np.dot(data.T,Y)

In [52]:
w_mat = np.dot(XT_X_INV,XT_Y)
w_mat

array([[ 0.20301973],
       [ 0.55215353],
       [-0.03855485]])

In [53]:
sum_se_OT2 = 0
sum_se_OT3 = 0
for i in range(len(Y)):
    sum_se_OT2 += (Y[i] - np.dot(w.T,data[i]))**2
    sum_se_OT3 += (Y[i] - np.dot(w_mat.T,data[i]))**2
MSE_OT2 = sum_se_OT2 / len(data)
MSE_OT3 = sum_se_OT3 / len(data)
print(f"MSE of linear regression : {MSE_OT2[0]}")
print(f"MSE of inversion matrix : {MSE_OT3[0]}")
# quite similar
print(f"difference : {MSE_OT2[0]-MSE_OT3[0]}")

MSE of linear regression : 0.16664229654020007
MSE of inversion matrix : 0.16664229654020077
difference : -6.938893903907228e-16
