# Titanic

In [1]:
import pandas as pd
train_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/train.csv"
train = pd.read_csv(train_url)
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [2]:
test_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/test.csv"
test = pd.read_csv(test_url)
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [3]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [4]:
train["Age"].mode()

0    24.0
dtype: float64

# T4

In [5]:
train["Age"] = train["Age"].fillna(train["Age"].mode()[0])

In [6]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   28.566970    0.523008   
std     257.353842    0.486592    0.836071   13.199572    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   24.000000    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [7]:
print(pd.unique(train["Embarked"]))
print(train["Embarked"].isna().sum())

['S' 'C' 'Q' nan]
2


# T5

In [8]:
train.loc[train["Embarked"] == "S", "Embarked"] = 0
train.loc[train["Embarked"] == "C", "Embarked"] = 1
train.loc[train["Embarked"] == "Q", "Embarked"] = 2
train["Embarked"] = train["Embarked"].fillna(train["Embarked"].mode()[0])

In [9]:
print(pd.unique(train["Sex"]))

['male' 'female']


In [10]:
train.loc[train["Sex"] == "male", "Sex"] = 0
train.loc[train["Sex"] == "female", "Sex"] = 1

# T6

In [11]:
import numpy as np
lr = 0.01
feature = ["Pclass","Sex","Age","Embarked"]
data = np.array(train[feature].values, dtype = float)
data = np.insert(data,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
data

array([[ 1.,  3.,  0., 22.,  0.],
       [ 1.,  1.,  1., 38.,  1.],
       [ 1.,  3.,  1., 26.,  0.],
       ...,
       [ 1.,  3.,  1., 24.,  0.],
       [ 1.,  1.,  0., 26.,  1.],
       [ 1.,  3.,  0., 32.,  2.]])

In [12]:
data = data/np.max(data, axis=0)
data

array([[1.        , 1.        , 0.        , 0.275     , 0.        ],
       [1.        , 0.33333333, 1.        , 0.475     , 0.5       ],
       [1.        , 1.        , 1.        , 0.325     , 0.        ],
       ...,
       [1.        , 1.        , 1.        , 0.3       , 0.        ],
       [1.        , 0.33333333, 0.        , 0.325     , 0.5       ],
       [1.        , 1.        , 0.        , 0.4       , 1.        ]])

In [13]:
Y = np.array(train[["Survived"]].values, dtype = float)
Y

array([[0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],

In [14]:
w = np.random.rand(len(feature)+1).reshape(-1,1)
w

array([[0.53197448],
       [0.43455931],
       [0.37094725],
       [0.99930367],
       [0.70528615]])

In [15]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [16]:
for epoch in range(1000):
    print(f"epoch : {epoch}")
    for j in range(len(w)):
        sum = 0
        for num in range(len(data)):
            sum += (Y[num][0] - sigmoid(np.dot(w.T,data[num])))*data[num][j]
        print(sum)
        w[j] = w[j] + lr*sum

epoch : 0
[-379.57102637]
[156.93110378]
[140.58617188]
[3.08667598]
[-3.79788274]
epoch : 1
[9.6640422]
[-64.39503105]
[69.13556428]
[8.26984852]
[-0.25268314]
epoch : 2
[23.74765223]
[-55.4725004]
[27.92452218]
[8.73982715]
[1.08817052]
epoch : 3
[28.17858449]
[-46.61381578]
[10.38952721]
[7.18584576]
[1.26334507]
epoch : 4
[27.89970441]
[-39.77470648]
[2.79037391]
[5.23109699]
[1.13954174]
epoch : 5
[26.42232147]
[-34.5403644]
[-0.61959421]
[3.23021173]
[0.92928205]
epoch : 6
[24.56757719]
[-30.24663165]
[-2.07984821]
[1.30752865]
[0.70088503]
epoch : 7
[22.59856433]
[-26.55186168]
[-2.5827764]
[-0.46447597]
[0.4846599]
epoch : 8
[20.64830944]
[-23.30426479]
[-2.61679379]
[-2.04261723]
[0.29446783]
epoch : 9
[18.79506652]
[-20.43603915]
[-2.43536989]
[-3.40737782]
[0.13520043]
epoch : 10
[17.08312077]
[-17.91067367]
[-2.17157932]
[-4.55764569]
[0.00665403]
epoch : 11
[15.53286547]
[-15.70000402]
[-1.89362109]
[-5.50488145]
[-0.09404797]
epoch : 12
[14.14821942]
[-13.77611927]
[-1.63

[-0.23527295]
[0.00965874]
[-0.76476677]
[-0.02190948]
epoch : 106
[0.44241054]
[-0.22896261]
[0.00953088]
[-0.74354095]
[-0.02125706]
epoch : 107
[0.43021498]
[-0.22282103]
[0.00939899]
[-0.72292216]
[-0.02062568]
epoch : 108
[0.41836386]
[-0.21684373]
[0.00926364]
[-0.70289208]
[-0.02001459]
epoch : 109
[0.40684702]
[-0.21102634]
[0.00912531]
[-0.68343302]
[-0.01942306]
epoch : 110
[0.39565462]
[-0.20536462]
[0.00898446]
[-0.66452787]
[-0.01885038]
epoch : 111
[0.38477711]
[-0.19985444]
[0.00884154]
[-0.64616006]
[-0.01829589]
epoch : 112
[0.37420528]
[-0.19449177]
[0.00869692]
[-0.62831357]
[-0.01775893]
epoch : 113
[0.36393016]
[-0.18927269]
[0.00855098]
[-0.61097288]
[-0.0172389]
epoch : 114
[0.35394312]
[-0.18419337]
[0.00840405]
[-0.59412299]
[-0.0167352]
epoch : 115
[0.34423575]
[-0.1792501]
[0.00825643]
[-0.57774935]
[-0.01624726]
epoch : 116
[0.33479993]
[-0.17443925]
[0.00810842]
[-0.5618379]
[-0.01577453]
epoch : 117
[0.32562777]
[-0.1697573]
[0.00796027]
[-0.54637503]
[-0.

[-0.01387489]
[0.00083062]
[-0.04365208]
[-0.00116131]
epoch : 210
[0.0254252]
[-0.01350231]
[0.00080872]
[-0.04247763]
[-0.00112992]
epoch : 211
[0.02474142]
[-0.01313972]
[0.00078738]
[-0.04133483]
[-0.00109939]
epoch : 212
[0.02407606]
[-0.01278688]
[0.00076659]
[-0.04022284]
[-0.00106969]
epoch : 213
[0.02342862]
[-0.01244351]
[0.00074634]
[-0.03914082]
[-0.00104079]
epoch : 214
[0.02279861]
[-0.01210937]
[0.00072662]
[-0.03808796]
[-0.00101268]
epoch : 215
[0.02218557]
[-0.01178419]
[0.00070742]
[-0.03706346]
[-0.00098533]
epoch : 216
[0.02158904]
[-0.01146775]
[0.00068871]
[-0.03606658]
[-0.00095873]
epoch : 217
[0.02100857]
[-0.01115981]
[0.00067049]
[-0.03509654]
[-0.00093285]
epoch : 218
[0.02044372]
[-0.01086013]
[0.00065274]
[-0.03415264]
[-0.00090766]
epoch : 219
[0.01989408]
[-0.01056851]
[0.00063545]
[-0.03323417]
[-0.00088317]
epoch : 220
[0.01935924]
[-0.01028471]
[0.00061862]
[-0.03234043]
[-0.00085933]
epoch : 221
[0.01883879]
[-0.01000854]
[0.00060223]
[-0.03147076]


[0.00162442]
[-0.00086391]
[5.26068519e-05]
[-0.00271296]
[-7.18582675e-05]
epoch : 312
[0.0015808]
[-0.00084072]
[5.11958083e-05]
[-0.0026401]
[-6.99279778e-05]
epoch : 313
[0.00153835]
[-0.00081814]
[4.98225723e-05]
[-0.0025692]
[-6.80495609e-05]
epoch : 314
[0.00149703]
[-0.00079617]
[4.84861329e-05]
[-0.00250021]
[-6.62216219e-05]
epoch : 315
[0.00145683]
[-0.00077479]
[4.71855063e-05]
[-0.00243307]
[-6.44428032e-05]
epoch : 316
[0.00141771]
[-0.00075399]
[4.59197346e-05]
[-0.00236773]
[-6.27117839e-05]
epoch : 317
[0.00137964]
[-0.00073374]
[4.46878856e-05]
[-0.00230414]
[-6.10272787e-05]
epoch : 318
[0.00134259]
[-0.00071404]
[4.34890519e-05]
[-0.00224227]
[-5.93880367e-05]
epoch : 319
[0.00130654]
[-0.00069487]
[4.23223502e-05]
[-0.00218205]
[-5.77928409e-05]
epoch : 320
[0.00127145]
[-0.00067621]
[4.11869208e-05]
[-0.00212346]
[-5.6240507e-05]
epoch : 321
[0.00123731]
[-0.00065805]
[4.0081927e-05]
[-0.00206643]
[-5.47298826e-05]
epoch : 322
[0.00120408]
[-0.00064038]
[3.9006554

[-0.0002158]
[-5.71435203e-06]
epoch : 405
[0.00012575]
[-6.6881414e-05]
[4.07684994e-06]
[-0.00021]
[-5.56090812e-06]
epoch : 406
[0.00012237]
[-6.50855469e-05]
[3.96738955e-06]
[-0.00020437]
[-5.41158468e-06]
epoch : 407
[0.00011908]
[-6.33379017e-05]
[3.86086786e-06]
[-0.00019888]
[-5.26627103e-06]
epoch : 408
[0.00011589]
[-6.16371833e-05]
[3.75720596e-06]
[-0.00019354]
[-5.12485951e-06]
epoch : 409
[0.00011277]
[-5.99821319e-05]
[3.65632714e-06]
[-0.00018834]
[-4.98724534e-06]
epoch : 410
[0.00010975]
[-5.83715211e-05]
[3.55815661e-06]
[-0.00018328]
[-4.85332652e-06]
epoch : 411
[0.0001068]
[-5.68041576e-05]
[3.46262175e-06]
[-0.00017836]
[-4.72300383e-06]
epoch : 412
[0.00010393]
[-5.52788802e-05]
[3.36965179e-06]
[-0.00017357]
[-4.59618067e-06]
epoch : 413
[0.00010114]
[-5.37945589e-05]
[3.27917781e-06]
[-0.00016891]
[-4.47276311e-06]
epoch : 414
[9.84248534e-05]
[-5.23500938e-05]
[3.19113291e-06]
[-0.00016438]
[-4.35265964e-06]
epoch : 415
[9.57819823e-05]
[-5.09444148e-05]
[3.

[1.27801567e-05]
[-6.79752993e-06]
[4.14385056e-07]
[-2.13437806e-05]
[-5.65169718e-07]
epoch : 490
[1.243699e-05]
[-6.61500601e-06]
[4.03258303e-07]
[-2.07706675e-05]
[-5.49994e-07]
epoch : 491
[1.21030379e-05]
[-6.43738315e-06]
[3.92430301e-07]
[-2.02129434e-05]
[-5.3522579e-07]
epoch : 492
[1.17780529e-05]
[-6.26452974e-06]
[3.8189303e-07]
[-1.9670195e-05]
[-5.20854135e-07]
epoch : 493
[1.14617943e-05]
[-6.0963177e-06]
[3.71638712e-07]
[-1.91420202e-05]
[-5.06868376e-07]
epoch : 494
[1.11540277e-05]
[-5.93262242e-06]
[3.61659741e-07]
[-1.86280278e-05]
[-4.9325815e-07]
epoch : 495
[1.08545251e-05]
[-5.77332258e-06]
[3.51948681e-07]
[-1.81278369e-05]
[-4.80013409e-07]
epoch : 496
[1.05630646e-05]
[-5.61830021e-06]
[3.42498422e-07]
[-1.76410768e-05]
[-4.67124289e-07]
epoch : 497
[1.02794303e-05]
[-5.46744041e-06]
[3.33301884e-07]
[-1.71673871e-05]
[-4.54581262e-07]
epoch : 498
[1.0003412e-05]
[-5.32063143e-06]
[3.24352291e-07]
[-1.67064166e-05]
[-4.42375042e-07]
epoch : 499
[9.7348052e

[-6.3669917e-07]
[3.88142131e-08]
[-1.99919027e-06]
[-5.29371732e-08]
epoch : 577
[1.16492551e-06]
[-6.19602844e-07]
[3.77719995e-08]
[-1.94550901e-06]
[-5.15157357e-08]
epoch : 578
[1.13364547e-06]
[-6.02965546e-07]
[3.67577507e-08]
[-1.89326916e-06]
[-5.01324586e-08]
epoch : 579
[1.10320538e-06]
[-5.86775055e-07]
[3.57707715e-08]
[-1.84243204e-06]
[-4.87863222e-08]
epoch : 580
[1.07358269e-06]
[-5.71019241e-07]
[3.48102478e-08]
[-1.79295998e-06]
[-4.74763378e-08]
epoch : 581
[1.04475536e-06]
[-5.55686544e-07]
[3.387556e-08]
[-1.74481631e-06]
[-4.62015292e-08]
epoch : 582
[1.01670214e-06]
[-5.40765535e-07]
[3.29659261e-08]
[-1.69796538e-06]
[-4.49609504e-08]
epoch : 583
[9.89402129e-07]
[-5.26245147e-07]
[3.20807509e-08]
[-1.65237244e-06]
[-4.37536762e-08]
epoch : 584
[9.62835211e-07]
[-5.12114659e-07]
[3.12193316e-08]
[-1.60800376e-06]
[-4.25788221e-08]
epoch : 585
[9.36981629e-07]
[-4.98363615e-07]
[3.03810574e-08]
[-1.56482644e-06]
[-4.14355209e-08]
epoch : 586
[9.11822244e-07]
[-4

[1.23654725e-08]
[-6.57696504e-09]
[4.00924294e-10]
[-2.06512229e-08]
[-5.46836312e-10]
epoch : 745
[1.20334402e-08]
[-6.40037531e-09]
[3.90180444e-10]
[-2.00966945e-08]
[-5.32145744e-10]
epoch : 746
[1.17103332e-08]
[-6.22851526e-09]
[3.7969905e-10]
[-1.95570814e-08]
[-5.17856147e-10]
epoch : 747
[1.13958808e-08]
[-6.06126162e-09]
[3.69492437e-10]
[-1.90319506e-08]
[-5.03958153e-10]
epoch : 748
[1.10898612e-08]
[-5.89850027e-09]
[3.59572039e-10]
[-1.85209107e-08]
[-4.90420884e-10]
epoch : 749
[1.07920949e-08]
[-5.74012107e-09]
[3.49929086e-10]
[-1.80235922e-08]
[-4.77253362e-10]
epoch : 750
[1.05023121e-08]
[-5.5860044e-09]
[3.40534934e-10]
[-1.7539624e-08]
[-4.64433339e-10]
epoch : 751
[1.02203413e-08]
[-5.43599804e-09]
[3.31385364e-10]
[-1.7068669e-08]
[-4.51962565e-10]
epoch : 752
[9.94588166e-09]
[-5.29004623e-09]
[3.22488924e-10]
[-1.66103505e-08]
[-4.39834891e-10]
epoch : 753
[9.67880606e-09]
[-5.14798322e-09]
[3.13830739e-10]
[-1.61643362e-08]
[-4.28018343e-10]
epoch : 754
[9.4

[-2.04255279e-09]
[-5.40886641e-11]
epoch : 830
[1.19018079e-09]
[-6.33031863e-10]
[3.85942389e-11]
[-1.98769587e-09]
[-5.26248767e-11]
epoch : 831
[1.15823742e-09]
[-6.16035611e-10]
[3.75522946e-11]
[-1.93432831e-09]
[-5.12202919e-11]
epoch : 832
[1.12712306e-09]
[-5.99481617e-10]
[3.65345532e-11]
[-1.88238765e-09]
[-4.98392161e-11]
epoch : 833
[1.09687816e-09]
[-5.83413262e-10]
[3.5543235e-11]
[-1.83182667e-09]
[-4.85049084e-11]
epoch : 834
[1.06740664e-09]
[-5.67750388e-10]
[3.46255247e-11]
[-1.78265058e-09]
[-4.72023393e-11]
epoch : 835
[1.03877068e-09]
[-5.52489138e-10]
[3.36751738e-11]
[-1.7347865e-09]
[-4.59369626e-11]
epoch : 836
[1.01085899e-09]
[-5.37650133e-10]
[3.2780112e-11]
[-1.68820596e-09]
[-4.46948589e-11]
epoch : 837
[9.83711668e-10]
[-5.23205965e-10]
[3.19034799e-11]
[-1.6428655e-09]
[-4.34960123e-11]
epoch : 838
[9.57331145e-10]
[-5.09166528e-10]
[3.10311776e-11]
[-1.59877674e-09]
[-4.23357599e-11]
epoch : 839
[9.31550115e-10]
[-4.95482086e-10]
[3.02123881e-11]
[-1.

[-1.96605621e-10]
[-5.20995747e-12]
epoch : 916
[1.14544138e-10]
[-6.09408912e-11]
[3.70437014e-12]
[-1.9131513e-10]
[-5.06709952e-12]
epoch : 917
[1.11484627e-10]
[-5.92836891e-11]
[3.61799479e-12]
[-1.86180862e-10]
[-4.92840491e-12]
epoch : 918
[1.08486387e-10]
[-5.77180942e-11]
[3.54116736e-12]
[-1.8118676e-10]
[-4.79737083e-12]
epoch : 919
[1.05571094e-10]
[-5.61299757e-11]
[3.42126327e-12]
[-1.76323622e-10]
[-4.66855721e-12]
epoch : 920
[1.0272394e-10]
[-5.46248879e-11]
[3.3297809e-12]
[-1.71589479e-10]
[-4.54407345e-12]
epoch : 921
[9.99784561e-11]
[-5.31818062e-11]
[3.25384164e-12]
[-1.66964033e-10]
[-4.41373327e-12]
epoch : 922
[9.73138792e-11]
[-5.17591664e-11]
[3.16291437e-12]
[-1.6249372e-10]
[-4.29720148e-12]
epoch : 923
[9.46820539e-11]
[-5.03383168e-11]
[3.07864845e-12]
[-1.58134825e-10]
[-4.18587387e-12]
epoch : 924
[9.21658722e-11]
[-4.90231744e-11]
[2.9912739e-12]
[-1.53885106e-10]
[-4.07343603e-12]
epoch : 925
[8.96790697e-11]
[-4.76988865e-11]
[2.91566771e-12]
[-1.49

[3.93352018e-13]
[-1.99816413e-11]
[-5.31921729e-13]


In [17]:
#predicting on train set
train_res = []
for num in range(len(data)):
    if sigmoid(np.dot(w.T,data[num])) >= 0.5:
        train_res.append(1)
    else:
        train_res.append(0)

In [18]:
train_res = np.array(train_res).reshape(-1,1)
train_res

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
    

In [19]:
sum = 0
for i in range(len(train_res)):
    if int(train_res[i][0]) == int(Y[i][0]):
        sum += 1
print(sum/len(train_res))

0.7811447811447811


In [20]:
test.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [21]:
test["Age"] = test["Age"].fillna(test["Age"].mode()[0])
print(pd.unique(test["Embarked"]))
print(test["Embarked"].isna().sum())

['Q' 'S' 'C']
0


In [22]:
test.loc[test["Embarked"] == "S", "Embarked"] = 0
test.loc[test["Embarked"] == "C", "Embarked"] = 1
test.loc[test["Embarked"] == "Q", "Embarked"] = 2
test["Embarked"] = test["Embarked"].fillna(test["Embarked"].mode()[0])
print(pd.unique(test["Sex"]))

['male' 'female']


In [23]:
test.loc[test["Sex"] == "male", "Sex"] = 0
test.loc[test["Sex"] == "female", "Sex"] = 1

In [24]:
X_test = np.array(test[feature].values, dtype = float)
X_test = np.insert(X_test,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
X_test = X_test/np.max(X_test, axis=0)
X_test

array([[1.        , 1.        , 0.        , 0.45394737, 1.        ],
       [1.        , 1.        , 1.        , 0.61842105, 0.        ],
       [1.        , 0.66666667, 0.        , 0.81578947, 1.        ],
       ...,
       [1.        , 1.        , 0.        , 0.50657895, 0.        ],
       [1.        , 1.        , 0.        , 0.27631579, 0.        ],
       [1.        , 1.        , 0.        , 0.27631579, 0.5       ]])

In [26]:
#predicting on test set
test_res = []
for num in range(len(X_test)):
    if sigmoid(np.dot(w.T,X_test[num])) >= 0.5:
        test_res.append(1)
    else:
        test_res.append(0)
test_res = np.array(test_res).reshape(-1,1)
print(test_res)

[[0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]


# T7

In [27]:
df_result = pd.DataFrame()
df_result = test[["PassengerId"]]
df_result["Survived"] = test_res.reshape(-1)
df_result

<ipython-input-27-1fd4da4a8654>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result["Survived"] = test_res.reshape(-1)


PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [28]:
#df_result.to_csv("submission.csv",index=False)

# T8

In [29]:
x1_x2 = []
x1_2 = []
for i in data:
    x1_x2.append(i[1]*i[2])
    x1_2.append(i[1]**2)
data = np.insert(data,1,np.array(x1_x2),axis=1)
data = np.insert(data,1,np.array(x1_2),axis=1)
data

array([[1.        , 1.        , 0.        , ..., 0.        , 0.275     ,
        0.        ],
       [1.        , 0.11111111, 0.33333333, ..., 1.        , 0.475     ,
        0.5       ],
       [1.        , 1.        , 1.        , ..., 1.        , 0.325     ,
        0.        ],
       ...,
       [1.        , 1.        , 1.        , ..., 1.        , 0.3       ,
        0.        ],
       [1.        , 0.11111111, 0.        , ..., 0.        , 0.325     ,
        0.5       ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.4       ,
        1.        ]])

In [30]:
w = np.random.rand(data.shape[1]).reshape(-1,1)
w

array([[0.78605207],
       [0.68334732],
       [0.61671153],
       [0.47051628],
       [0.62220127],
       [0.95770906],
       [0.46096536]])

In [31]:
for epoch in range(1000):
    print(f"epoch : {epoch}")
    for j in range(len(w)):
        sum = 0
        for num in range(len(data)):
            sum += (Y[num][0] - sigmoid(np.dot(w.T,data[num])))*data[num][j]
        print(sum)
        w[j] = w[j] + lr*sum

epoch : 0
[-464.18895898]
[94.48503532]
[67.57981152]
[33.61520386]
[93.05670852]
[17.60348676]
[3.19430258]
epoch : 1
[30.46209898]
[-108.14174342]
[3.67243282]
[13.84484304]
[44.88264834]
[17.34482207]
[4.87565366]
epoch : 2
[38.57656595]
[-80.32077006]
[-17.4924389]
[5.93410496]
[19.21922357]
[13.61474543]
[4.72440137]
epoch : 3
[37.60126663]
[-61.38539236]
[-21.40969997]
[4.56553232]
[8.52505555]
[8.78207189]
[4.00085123]
epoch : 4
[33.24425842]
[-47.99951753]
[-19.71985619]
[4.45787581]
[4.68157599]
[3.86042384]
[3.16016746]
epoch : 5
[27.84827509]
[-37.40712168]
[-16.61522051]
[4.1681536]
[3.59022824]
[-0.48227747]
[2.40132314]
epoch : 6
[22.6488592]
[-28.79481032]
[-13.63426423]
[3.66783811]
[3.48070039]
[-3.91956688]
[1.79574106]
epoch : 7
[18.23756206]
[-21.9723]
[-11.23906924]
[3.14057431]
[3.62677842]
[-6.43406318]
[1.34086191]
epoch : 8
[14.75118358]
[-16.74229874]
[-9.4561672]
[2.69258954]
[3.76852696]
[-8.16830136]
[1.00661614]
epoch : 9
[12.09558498]
[-12.82341211]
[-8.1

[0.03012585]
epoch : 80
[0.3944761]
[-0.06930718]
[-1.88042256]
[0.16953387]
[1.60561517]
[-1.32856821]
[0.0303384]
epoch : 81
[0.38171255]
[-0.05952436]
[-1.86004039]
[0.15961361]
[1.58932248]
[-1.291025]
[0.03052183]
epoch : 82
[0.3694357]
[-0.04996979]
[-1.83997997]
[0.14984418]
[1.573251]
[-1.25465794]
[0.03067779]
epoch : 83
[0.35762739]
[-0.04063734]
[-1.82023345]
[0.14022251]
[1.5573969]
[-1.21942638]
[0.03080784]
epoch : 84
[0.34627019]
[-0.03152105]
[-1.80079326]
[0.13074563]
[1.5417564]
[-1.18529125]
[0.03091343]
epoch : 85
[0.33534738]
[-0.02261512]
[-1.78165214]
[0.12141067]
[1.52632584]
[-1.15221501]
[0.03099597]
epoch : 86
[0.32484288]
[-0.01391391]
[-1.76280307]
[0.11221484]
[1.51110158]
[-1.12016154]
[0.03105677]
epoch : 87
[0.31474127]
[-0.00541194]
[-1.7442393]
[0.1031554]
[1.49608009]
[-1.0890961]
[0.03109709]
epoch : 88
[0.30502772]
[0.00289611]
[-1.7259543]
[0.09422974]
[1.4812579]
[-1.05898528]
[0.03111809]
epoch : 89
[0.295688]
[0.01101541]
[-1.70794179]
[0.08543

[-0.31284068]
[0.77108298]
[-0.17351385]
[0.01648125]
epoch : 162
[0.09505897]
[0.31104603]
[-0.86951138]
[-0.31613851]
[0.76484807]
[-0.1698831]
[0.01626266]
epoch : 163
[0.09506571]
[0.31293154]
[-0.86231292]
[-0.31939447]
[0.75867743]
[-0.16634729]
[0.01604548]
epoch : 164
[0.09509505]
[0.31478487]
[-0.85519108]
[-0.32260909]
[0.75257022]
[-0.16290374]
[0.01582971]
epoch : 165
[0.09514606]
[0.31660664]
[-0.84814481]
[-0.32578291]
[0.74652562]
[-0.15954988]
[0.01561537]
epoch : 166
[0.09521782]
[0.31839745]
[-0.84117309]
[-0.32891646]
[0.74054282]
[-0.15628319]
[0.01540247]
epoch : 167
[0.09530947]
[0.32015789]
[-0.83427493]
[-0.33201025]
[0.73462102]
[-0.15310124]
[0.01519102]
epoch : 168
[0.09542015]
[0.32188854]
[-0.82744932]
[-0.33506481]
[0.72875943]
[-0.15000168]
[0.01498103]
epoch : 169
[0.09554905]
[0.32358996]
[-0.8206953]
[-0.33808061]
[0.7229573]
[-0.1469822]
[0.01477251]
epoch : 170
[0.09569538]
[0.32526271]
[-0.81401192]
[-0.34105817]
[0.71721384]
[-0.14404058]
[0.014565

[-0.04726541]
[0.0034836]
epoch : 242
[0.12251377]
[0.39451174]
[-0.4716354]
[-0.47954953]
[0.42021448]
[-0.04673507]
[0.00337233]
epoch : 243
[0.12289273]
[0.39498948]
[-0.46831646]
[-0.48068212]
[0.41730735]
[-0.04621573]
[0.00326209]
epoch : 244
[0.12326905]
[0.39545814]
[-0.46502669]
[-0.48179858]
[0.4144252]
[-0.04570713]
[0.00315287]
epoch : 245
[0.12364269]
[0.39591786]
[-0.46176576]
[-0.4828991]
[0.41156776]
[-0.04520899]
[0.00304467]
epoch : 246
[0.1240136]
[0.39636873]
[-0.45853337]
[-0.48398383]
[0.40873479]
[-0.04472106]
[0.00293747]
epoch : 247
[0.12438177]
[0.39681088]
[-0.45532922]
[-0.48505294]
[0.40592604]
[-0.04424307]
[0.00283128]
epoch : 248
[0.12474714]
[0.3972444]
[-0.45215301]
[-0.48610661]
[0.40314124]
[-0.04377479]
[0.00272607]
epoch : 249
[0.1251097]
[0.39766942]
[-0.44900444]
[-0.48714499]
[0.40038016]
[-0.04331597]
[0.00262185]
epoch : 250
[0.12546942]
[0.39808603]
[-0.44588321]
[-0.48816825]
[0.39764256]
[-0.04286638]
[0.0025186]
epoch : 251
[0.12582626]
[0

[0.25102915]
[-0.02507517]
[-0.00278491]
epoch : 322
[0.14350867]
[0.41120979]
[-0.27785679]
[-0.53060773]
[0.24949753]
[-0.02493926]
[-0.00283666]
epoch : 323
[0.14365646]
[0.41121338]
[-0.27614191]
[-0.53085888]
[0.24797761]
[-0.0248051]
[-0.0028879]
epoch : 324
[0.14380177]
[0.41121325]
[-0.27444028]
[-0.53110288]
[0.24646928]
[-0.02467266]
[-0.00293863]
epoch : 325
[0.14394464]
[0.41120944]
[-0.27275179]
[-0.5313398]
[0.24497243]
[-0.02454189]
[-0.00298887]
epoch : 326
[0.14408506]
[0.41120199]
[-0.27107631]
[-0.5315697]
[0.24348697]
[-0.02441278]
[-0.00303862]
epoch : 327
[0.14422306]
[0.41119093]
[-0.26941374]
[-0.53179265]
[0.2420128]
[-0.02428528]
[-0.00308788]
epoch : 328
[0.14435866]
[0.41117631]
[-0.26776396]
[-0.53200872]
[0.24054981]
[-0.02415937]
[-0.00313666]
epoch : 329
[0.14449188]
[0.41115814]
[-0.26612685]
[-0.53221797]
[0.23909791]
[-0.02403501]
[-0.00318496]
epoch : 330
[0.14462272]
[0.41113648]
[-0.26450229]
[-0.53242048]
[0.237657]
[-0.02391217]
[-0.00323278]
epo

[-0.53296629]
[0.15839144]
[-0.01781488]
[-0.00563923]
epoch : 402
[0.14884686]
[0.40226916]
[-0.17443069]
[-0.53281946]
[0.15754002]
[-0.01775392]
[-0.00566187]
epoch : 403
[0.14884651]
[0.40206626]
[-0.17348285]
[-0.53266927]
[0.15669459]
[-0.01769344]
[-0.00568425]
epoch : 404
[0.14884486]
[0.40186167]
[-0.17254172]
[-0.53251575]
[0.15585508]
[-0.01763342]
[-0.00570639]
epoch : 405
[0.14884192]
[0.4016554]
[-0.17160724]
[-0.53235893]
[0.15502147]
[-0.01757385]
[-0.00572827]
epoch : 406
[0.14883772]
[0.40144748]
[-0.17067936]
[-0.53219886]
[0.1541937]
[-0.01751474]
[-0.00574992]
epoch : 407
[0.14883225]
[0.40123792]
[-0.16975802]
[-0.53203555]
[0.15337172]
[-0.01745608]
[-0.00577132]
epoch : 408
[0.14882553]
[0.40102674]
[-0.16884318]
[-0.53186905]
[0.15255549]
[-0.01739786]
[-0.00579248]
epoch : 409
[0.14881758]
[0.40081395]
[-0.16793478]
[-0.53169937]
[0.15174497]
[-0.01734007]
[-0.00581341]
epoch : 410
[0.14880839]
[0.40059957]
[-0.16703277]
[-0.53152656]
[0.1509401]
[-0.01728271]

[0.1068724]
[-0.01413198]
[-0.00679039]
epoch : 480
[0.14568578]
[0.38245861]
[-0.11716019]
[-0.51317825]
[0.1063726]
[-0.01409548]
[-0.00679865]
epoch : 481
[0.14561282]
[0.38216474]
[-0.11660538]
[-0.51284574]
[0.10587609]
[-0.01405918]
[-0.00680677]
epoch : 482
[0.14553924]
[0.38187013]
[-0.11605424]
[-0.5125117]
[0.10538286]
[-0.01402309]
[-0.00681477]
epoch : 483
[0.14546504]
[0.38157479]
[-0.11550675]
[-0.51217615]
[0.10489287]
[-0.0139872]
[-0.00682264]
epoch : 484
[0.14539022]
[0.38127874]
[-0.11496288]
[-0.51183911]
[0.10440612]
[-0.01395151]
[-0.00683038]
epoch : 485
[0.14531479]
[0.38098198]
[-0.1144226]
[-0.51150058]
[0.10392256]
[-0.01391602]
[-0.006838]
epoch : 486
[0.14523876]
[0.38068451]
[-0.11388589]
[-0.51116059]
[0.10344218]
[-0.01388073]
[-0.00684549]
epoch : 487
[0.14516213]
[0.38038635]
[-0.11335273]
[-0.51081915]
[0.10296496]
[-0.01384563]
[-0.00685285]
epoch : 488
[0.14508492]
[0.38008751]
[-0.11282307]
[-0.51047628]
[0.10249087]
[-0.01381073]
[-0.0068601]
epoc

[-0.48370902]
[0.07589273]
[-0.01176915]
[-0.00711454]
epoch : 559
[0.13840827]
[0.3575691]
[-0.08279676]
[-0.48329694]
[0.07559204]
[-0.01174476]
[-0.00711522]
epoch : 560
[0.13830125]
[0.35723907]
[-0.08246347]
[-0.48288426]
[0.07529322]
[-0.01172047]
[-0.00711583]
epoch : 561
[0.13819396]
[0.35690883]
[-0.08213226]
[-0.48247099]
[0.07499626]
[-0.0116963]
[-0.00711637]
epoch : 562
[0.1380864]
[0.35657836]
[-0.08180311]
[-0.48205714]
[0.07470114]
[-0.01167223]
[-0.00711685]
epoch : 563
[0.13797858]
[0.35624767]
[-0.08147602]
[-0.48164272]
[0.07440785]
[-0.01164828]
[-0.00711726]
epoch : 564
[0.1378705]
[0.35591677]
[-0.08115095]
[-0.48122773]
[0.07411638]
[-0.01162444]
[-0.0071176]
epoch : 565
[0.13776217]
[0.35558566]
[-0.08082791]
[-0.48081219]
[0.07382672]
[-0.0116007]
[-0.00711788]
epoch : 566
[0.13765358]
[0.35525435]
[-0.08050688]
[-0.4803961]
[0.07353885]
[-0.01157707]
[-0.0071181]
epoch : 567
[0.13754474]
[0.35492284]
[-0.08018784]
[-0.47997947]
[0.07325277]
[-0.01155354]
[-0.

[0.33111431]
[-0.06186624]
[-0.44945457]
[0.05681419]
[-0.01011521]
[-0.00699559]
epoch : 639
[0.12922335]
[0.33077807]
[-0.06165978]
[-0.44901666]
[0.05662884]
[-0.01009773]
[-0.00699235]
epoch : 640
[0.12910311]
[0.33044186]
[-0.06145454]
[-0.44857865]
[0.05644456]
[-0.01008032]
[-0.00698906]
epoch : 641
[0.12898279]
[0.33010571]
[-0.06125049]
[-0.44814055]
[0.05626136]
[-0.01006297]
[-0.00698575]
epoch : 642
[0.1288624]
[0.3297696]
[-0.06104763]
[-0.44770237]
[0.05607922]
[-0.01004569]
[-0.0069824]
epoch : 643
[0.12874192]
[0.32943355]
[-0.06084596]
[-0.4472641]
[0.05589814]
[-0.01002847]
[-0.00697902]
epoch : 644
[0.12862138]
[0.32909754]
[-0.06064545]
[-0.44682575]
[0.05571811]
[-0.01001131]
[-0.0069756]
epoch : 645
[0.12850076]
[0.3287616]
[-0.06044612]
[-0.44638734]
[0.05553912]
[-0.00999422]
[-0.00697216]
epoch : 646
[0.12838006]
[0.32842571]
[-0.06024794]
[-0.44594885]
[0.05536118]
[-0.0099772]
[-0.00696868]
epoch : 647
[0.1282593]
[0.32808988]
[-0.06005091]
[-0.4455103]
[0.05

[-0.00665641]
epoch : 718
[0.11959515]
[0.30452462]
[-0.04857471]
[-0.41443573]
[0.0448726]
[-0.00889479]
[-0.00665129]
epoch : 719
[0.1194729]
[0.30419812]
[-0.04844318]
[-0.4140017]
[0.04475431]
[-0.00888148]
[-0.00664616]
epoch : 720
[0.11935068]
[0.30387182]
[-0.04831236]
[-0.41356783]
[0.04463666]
[-0.00886821]
[-0.00664101]
epoch : 721
[0.11922847]
[0.3035457]
[-0.04818224]
[-0.41313413]
[0.04451965]
[-0.00885497]
[-0.00663584]
epoch : 722
[0.11910628]
[0.30321976]
[-0.04805282]
[-0.4127006]
[0.04440325]
[-0.00884178]
[-0.00663066]
epoch : 723
[0.11898412]
[0.30289402]
[-0.04792409]
[-0.41226725]
[0.04428748]
[-0.00882863]
[-0.00662546]
epoch : 724
[0.11886198]
[0.30256847]
[-0.04779605]
[-0.41183407]
[0.04417232]
[-0.00881552]
[-0.00662025]
epoch : 725
[0.11873986]
[0.3022431]
[-0.04766869]
[-0.41140107]
[0.04405778]
[-0.00880245]
[-0.00661503]
epoch : 726
[0.11861777]
[0.30191794]
[-0.04754202]
[-0.41096825]
[0.04394384]
[-0.00878942]
[-0.00660979]
epoch : 727
[0.1184957]
[0.30

[-0.04012845]
[-0.38122775]
[0.03726934]
[-0.00796301]
[-0.00621645]
epoch : 797
[0.11005596]
[0.27938343]
[-0.04004032]
[-0.38081218]
[0.0371899]
[-0.00795229]
[-0.00621055]
epoch : 798
[0.10993741]
[0.27907453]
[-0.03995261]
[-0.3803969]
[0.03711084]
[-0.00794159]
[-0.00620466]
epoch : 799
[0.10981894]
[0.27876589]
[-0.03986534]
[-0.37998192]
[0.03703216]
[-0.00793091]
[-0.00619875]
epoch : 800
[0.10970053]
[0.27845749]
[-0.03977848]
[-0.37956724]
[0.03695385]
[-0.00792027]
[-0.00619284]
epoch : 801
[0.1095822]
[0.27814935]
[-0.03969204]
[-0.37915285]
[0.03687592]
[-0.00790964]
[-0.00618693]
epoch : 802
[0.10946393]
[0.27784147]
[-0.03960602]
[-0.37873876]
[0.03679837]
[-0.00789905]
[-0.00618101]
epoch : 803
[0.10934573]
[0.27753384]
[-0.03952041]
[-0.37832496]
[0.03672118]
[-0.00788848]
[-0.00617509]
epoch : 804
[0.10922761]
[0.27722646]
[-0.03943521]
[-0.37791147]
[0.03664435]
[-0.00787794]
[-0.00616916]
epoch : 805
[0.10910956]
[0.27691934]
[-0.03935042]
[-0.37749828]
[0.0365679]


[-0.34937253]
[0.03199841]
[-0.00718841]
[-0.0057414]
epoch : 876
[0.10093325]
[0.25579028]
[-0.03422878]
[-0.34898271]
[0.03194274]
[-0.00717944]
[-0.00573534]
epoch : 877
[0.10082124]
[0.25550248]
[-0.0341675]
[-0.34859324]
[0.0318873]
[-0.00717049]
[-0.00572927]
epoch : 878
[0.10070931]
[0.25521496]
[-0.03410649]
[-0.34820413]
[0.03183209]
[-0.00716156]
[-0.00572321]
epoch : 879
[0.10059748]
[0.25492772]
[-0.03404572]
[-0.34781536]
[0.03177711]
[-0.00715264]
[-0.00571715]
epoch : 880
[0.10048575]
[0.25464076]
[-0.03398521]
[-0.34742694]
[0.03172236]
[-0.00714374]
[-0.00571109]
epoch : 881
[0.1003741]
[0.25435408]
[-0.03392496]
[-0.34703888]
[0.03166783]
[-0.00713486]
[-0.00570503]
epoch : 882
[0.10026255]
[0.25406767]
[-0.03386495]
[-0.34665116]
[0.03161353]
[-0.007126]
[-0.00569898]
epoch : 883
[0.1001511]
[0.25378154]
[-0.0338052]
[-0.34626381]
[0.03155945]
[-0.00711716]
[-0.00569292]
epoch : 884
[0.10003974]
[0.2534957]
[-0.03374569]
[-0.3458768]
[0.03150559]
[-0.00710833]
[-0.00

[-0.0052613]
epoch : 956
[0.09227784]
[0.23365104]
[-0.03002487]
[-0.31895788]
[0.02813094]
[-0.00651522]
[-0.0052554]
epoch : 957
[0.09217369]
[0.23338567]
[-0.02997993]
[-0.3185973]
[0.02809008]
[-0.00650752]
[-0.0052495]
epoch : 958
[0.09206964]
[0.23312058]
[-0.02993514]
[-0.31823709]
[0.02804937]
[-0.00649983]
[-0.00524361]
epoch : 959
[0.09196569]
[0.23285577]
[-0.02989052]
[-0.31787724]
[0.02800879]
[-0.00649215]
[-0.00523772]
epoch : 960
[0.09186184]
[0.23259125]
[-0.02984605]
[-0.31751777]
[0.02796835]
[-0.00648448]
[-0.00523183]
epoch : 961
[0.09175809]
[0.232327]
[-0.02980174]
[-0.31715866]
[0.02792805]
[-0.00647683]
[-0.00522595]
epoch : 962
[0.09165445]
[0.23206303]
[-0.02975759]
[-0.31679991]
[0.02788789]
[-0.00646919]
[-0.00522007]
epoch : 963
[0.09155091]
[0.23179934]
[-0.02971358]
[-0.31644154]
[0.02784787]
[-0.00646156]
[-0.00521419]
epoch : 964
[0.09144747]
[0.23153593]
[-0.02966973]
[-0.31608353]
[0.02780798]
[-0.00645395]
[-0.00520832]
epoch : 965
[0.09134413]
[0.2

In [32]:
#predicting on train set
train_res = []
for num in range(len(data)):
    if sigmoid(np.dot(w.T,data[num])) >= 0.5:
        train_res.append(1)
    else:
        train_res.append(0)
train_res = np.array(train_res).reshape(-1,1)
sum = 0
for i in range(len(train_res)):
    if int(train_res[i][0]) == int(Y[i][0]):
        sum += 1
print(f"accuracy : {sum/len(train_res)}")
# a bit better than before

accuracy : 0.8013468013468014


In [33]:
feature = ["Pclass","Sex","Age","Embarked"]
X_test = np.array(test[feature].values, dtype = float)
X_test = np.insert(X_test,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
X_test = X_test/np.max(X_test, axis=0)
X_test

array([[1.        , 1.        , 0.        , 0.45394737, 1.        ],
       [1.        , 1.        , 1.        , 0.61842105, 0.        ],
       [1.        , 0.66666667, 0.        , 0.81578947, 1.        ],
       ...,
       [1.        , 1.        , 0.        , 0.50657895, 0.        ],
       [1.        , 1.        , 0.        , 0.27631579, 0.        ],
       [1.        , 1.        , 0.        , 0.27631579, 0.5       ]])

In [34]:
x1_x2 = []
x1_2 = []
for i in X_test:
    x1_x2.append(i[1]*i[2])
    x1_2.append(i[1]**2)
X_test = np.insert(X_test,1,np.array(x1_x2),axis=1)
X_test = np.insert(X_test,1,np.array(x1_2),axis=1)
X_test

array([[1.        , 1.        , 0.        , ..., 0.        , 0.45394737,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 0.61842105,
        0.        ],
       [1.        , 0.44444444, 0.        , ..., 0.        , 0.81578947,
        1.        ],
       ...,
       [1.        , 1.        , 0.        , ..., 0.        , 0.50657895,
        0.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.27631579,
        0.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.27631579,
        0.5       ]])

In [35]:
#predicting on test set
test_res = []
for num in range(len(X_test)):
    if sigmoid(np.dot(w.T,X_test[num])) >= 0.5:
        test_res.append(1)
    else:
        test_res.append(0)
test_res = np.array(test_res).reshape(-1,1)
print(test_res)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]


In [36]:
df_result = pd.DataFrame()
df_result = test[["PassengerId"]]
df_result["Survived"] = test_res.reshape(-1)
df_result

<ipython-input-36-1fd4da4a8654>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result["Survived"] = test_res.reshape(-1)


PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [37]:
#df_result.to_csv("submission2.csv",index=False)

In [38]:
"""
after adding to kaggle. as you can see from the picture T8, 
the model doesn't overfitting to train set as my assumption (before fitting) 
and model a bit better accuracy than T6
"""

# T9

In [39]:
import numpy as np
lr = 0.01
feature = ["Sex","Age"]
data = np.array(train[feature].values, dtype = float)
data = np.insert(data,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
data = data/np.max(data, axis=0)
w = np.random.rand(len(feature)+1).reshape(-1,1)
data


array([[1.   , 0.   , 0.275],
       [1.   , 1.   , 0.475],
       [1.   , 1.   , 0.325],
       ...,
       [1.   , 1.   , 0.3  ],
       [1.   , 0.   , 0.325],
       [1.   , 0.   , 0.4  ]])

In [40]:
for epoch in range(1000):
    print(f"epoch : {epoch}")
    for j in range(len(w)):
        sum = 0
        for num in range(len(data)):
            sum += (Y[num][0] - sigmoid(np.dot(w.T,data[num])))*data[num][j]
        print(sum)
        w[j] = w[j] + lr*sum

epoch : 0
[-356.28400338]
[185.66254407]
[44.90190663]
epoch : 1
[112.57345615]
[-19.02074084]
[-15.19249277]
epoch : 2
[-23.24358972]
[7.81893475]
[-0.40810197]
epoch : 3
[7.47591578]
[-1.49934368]
[-3.97857482]
epoch : 4
[-0.56448496]
[0.53037132]
[-2.85772088]
epoch : 5
[1.47564517]
[-0.10052171]
[-2.96033144]
epoch : 6
[0.91881992]
[0.00404094]
[-2.76409193]
epoch : 7
[1.02036414]
[-0.05402388]
[-2.65608949]
epoch : 8
[0.94834254]
[-0.05519851]
[-2.53487664]
epoch : 9
[0.91908187]
[-0.06205031]
[-2.42506269]
epoch : 10
[0.87865988]
[-0.06223434]
[-2.31937859]
epoch : 11
[0.84186793]
[-0.06115802]
[-2.2190171]
epoch : 12
[0.80543464]
[-0.05877102]
[-2.12317237]
epoch : 13
[0.77048128]
[-0.05588415]
[-2.03166054]
epoch : 14
[0.73685162]
[-0.05275984]
[-1.94420741]
epoch : 15
[0.70462986]
[-0.04960458]
[-1.86060767]
epoch : 16
[0.67378684]
[-0.04652088]
[-1.78066947]
epoch : 17
[0.64429308]
[-0.04356718]
[-1.70421978]
epoch : 18
[0.61610298]
[-0.04077111]
[-1.63109748]
epoch : 19
[0.5

[-4.23018116e-05]
[-0.00378329]
epoch : 159
[0.00133929]
[-4.050745e-05]
[-0.00362325]
epoch : 160
[0.00128263]
[-3.87894034e-05]
[-0.00346998]
epoch : 161
[0.00122837]
[-3.71444094e-05]
[-0.00332319]
epoch : 162
[0.00117641]
[-3.55693465e-05]
[-0.00318262]
epoch : 163
[0.00112664]
[-3.40612278e-05]
[-0.00304799]
epoch : 164
[0.00107898]
[-3.26171952e-05]
[-0.00291905]
epoch : 165
[0.00103334]
[-3.12345135e-05]
[-0.00279557]
epoch : 166
[0.00098963]
[-2.99105655e-05]
[-0.00267732]
epoch : 167
[0.00094776]
[-2.86428462e-05]
[-0.00256406]
epoch : 168
[0.00090767]
[-2.74289586e-05]
[-0.0024556]
epoch : 169
[0.00086927]
[-2.62666084e-05]
[-0.00235172]
epoch : 170
[0.0008325]
[-2.51535998e-05]
[-0.00225224]
epoch : 171
[0.00079728]
[-2.40878313e-05]
[-0.00215697]
epoch : 172
[0.00076356]
[-2.30672914e-05]
[-0.00206573]
epoch : 173
[0.00073126]
[-2.20900547e-05]
[-0.00197835]
epoch : 174
[0.00070032]
[-2.11542785e-05]
[-0.00189466]
epoch : 175
[0.0006707]
[-2.02581987e-05]
[-0.00181452]
epoc

[3.59145333e-06]
[-1.08332366e-07]
[-9.71660444e-06]
epoch : 297
[3.4395344e-06]
[-1.03749854e-07]
[-9.30559097e-06]
epoch : 298
[3.29404174e-06]
[-9.93612039e-08]
[-8.91196343e-06]
epoch : 299
[3.15470338e-06]
[-9.51582049e-08]
[-8.53498637e-06]
epoch : 300
[3.02125902e-06]
[-9.11329646e-08]
[-8.17395549e-06]
epoch : 301
[2.89345947e-06]
[-8.72780329e-08]
[-7.82819625e-06]
epoch : 302
[2.77106576e-06]
[-8.35861065e-08]
[-7.49706268e-06]
epoch : 303
[2.65384938e-06]
[-8.00503949e-08]
[-7.1799361e-06]
epoch : 304
[2.54159124e-06]
[-7.66642415e-08]
[-6.87622402e-06]
epoch : 305
[2.43408158e-06]
[-7.34212869e-08]
[-6.58535895e-06]
epoch : 306
[2.3311197e-06]
[-7.03155727e-08]
[-6.30679754e-06]
epoch : 307
[2.23251309e-06]
[-6.73412077e-08]
[-6.04001932e-06]
epoch : 308
[2.1380775e-06]
[-6.44926431e-08]
[-5.78452581e-06]
epoch : 309
[2.04763658e-06]
[-6.17645954e-08]
[-5.53983973e-06]
epoch : 310
[1.96102136e-06]
[-5.91519616e-08]
[-5.30550391e-06]
epoch : 311
[1.87806989e-06]
[-5.66497916

[1.48391206e-08]
[-4.47601289e-10]
[-4.0146995e-08]
epoch : 424
[1.42114726e-08]
[-4.28694635e-10]
[-3.8448793e-08]
epoch : 425
[1.36102881e-08]
[-4.10549594e-10]
[-3.68223877e-08]
epoch : 426
[1.30345741e-08]
[-3.93155841e-10]
[-3.52648038e-08]
epoch : 427
[1.24832334e-08]
[-3.76548126e-10]
[-3.37731078e-08]
epoch : 428
[1.1955165e-08]
[-3.60607766e-10]
[-3.23445003e-08]
epoch : 429
[1.14494653e-08]
[-3.4535963e-10]
[-3.09762994e-08]
epoch : 430
[1.0965165e-08]
[-3.30748318e-10]
[-2.96660175e-08]
epoch : 431
[1.05013346e-08]
[-3.16766835e-10]
[-2.84111388e-08]
epoch : 432
[1.00571175e-08]
[-3.0334224e-10]
[-2.72093482e-08]
epoch : 433
[9.63172286e-09]
[-2.90516722e-10]
[-2.6058387e-08]
epoch : 434
[9.22428414e-09]
[-2.78243317e-10]
[-2.49561184e-08]
epoch : 435
[8.83406523e-09]
[-2.66457301e-10]
[-2.39004694e-08]
epoch : 436
[8.46043613e-09]
[-2.55206856e-10]
[-2.28894656e-08]
epoch : 437
[8.10253134e-09]
[-2.44412934e-10]
[-2.19212423e-08]
epoch : 438
[7.7597811e-09]
[-2.34051223e-10

[-1.64379621e-12]
[-1.45710277e-10]
epoch : 554
[5.15475718e-11]
[-1.54842805e-12]
[-1.39543765e-10]
epoch : 555
[4.94377594e-11]
[-1.50646162e-12]
[-1.33630912e-10]
epoch : 556
[4.73067141e-11]
[-1.41942014e-12]
[-1.27993394e-10]
epoch : 557
[4.52580751e-11]
[-1.33382194e-12]
[-1.22560462e-10]
epoch : 558
[4.34142167e-11]
[-1.31639144e-12]
[-1.17388196e-10]
epoch : 559
[4.15687207e-11]
[-1.2420065e-12]
[-1.12422086e-10]
epoch : 560
[3.97996636e-11]
[-1.19515509e-12]
[-1.07664544e-10]
epoch : 561
[3.80951659e-11]
[-1.14441789e-12]
[-1.03115988e-10]
epoch : 562
[3.6502773e-11]
[-1.09801057e-12]
[-9.87468995e-11]
epoch : 563
[3.49550944e-11]
[-1.03339559e-12]
[-9.45646755e-11]
epoch : 564
[3.34657024e-11]
[-1.01629816e-12]
[-9.05687886e-11]
epoch : 565
[3.2093328e-11]
[-9.74553771e-13]
[-8.67515226e-11]
epoch : 566
[3.07078807e-11]
[-9.3691721e-13]
[-8.30729929e-11]
epoch : 567
[2.93912672e-11]
[-8.8240526e-13]
[-7.95684907e-11]
epoch : 568
[2.81696888e-11]
[-8.48543458e-13]
[-7.62100383

[1.58373314e-13]
[-8.77076189e-15]
[-4.26464419e-13]
epoch : 689
[1.52960977e-13]
[-1.687539e-14]
[-4.09616785e-13]
epoch : 690
[1.30201405e-13]
[-7.43849426e-15]
[-3.84359211e-13]
epoch : 691
[1.27231559e-13]
[-1.33226763e-14]
[-3.66970343e-13]
epoch : 692
[1.2703727e-13]
[-1.15463195e-14]
[-3.51579876e-13]
epoch : 693
[1.30367939e-13]
[-1.60982339e-14]
[-3.40616424e-13]
epoch : 694
[1.00502939e-13]
[-2.04281037e-14]
[-3.2727987e-13]
epoch : 695
[1.11743947e-13]
[-2.08721929e-14]
[-3.09197112e-13]
epoch : 696
[9.9670272e-14]
[-9.2148511e-15]
[-2.84841595e-13]
epoch : 697
[1.23678845e-13]
[-2.54241073e-14]
[-2.77194934e-13]
epoch : 698
[1.07663878e-13]
[-1.01030295e-14]
[-2.73697731e-13]
epoch : 699
[8.15736367e-14]
[-1.14352972e-14]
[-2.58029709e-13]
epoch : 700
[8.97892871e-14]
[-1.28785871e-14]
[-2.46067056e-13]
epoch : 701
[7.68274333e-14]
[3.21964677e-15]
[-2.22655228e-13]
epoch : 702
[1.04055653e-13]
[-1.16573418e-14]
[-2.36005659e-13]
epoch : 703
[6.76125822e-14]
[-1.08801856e-1

[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 817
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 818
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 819
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 820
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 821
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 822
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 823
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 824
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 825
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 826
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 827
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 828
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 829
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 830
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 831
[-1.98452366e-14]
[1.27675648e-1

[-9.52016244e-15]
epoch : 945
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 946
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 947
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 948
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 949
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 950
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 951
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 952
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 953
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 954
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 955
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 956
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 957
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 958
[2.51465515e-14]
[-2.44249065e-15]
[-9.52016244e-15]
epoch : 959
[-1.98452366e-14]
[1.27675648e-14]
[8.61810623e-15]
epoch : 960
[2.

In [41]:
w

array([[-1.37227573],
       [ 2.50861377],
       [-0.23307829]])

In [42]:
#predicting on train set
train_res = []
for num in range(len(data)):
    if sigmoid(np.dot(data[num],w)) >= 0.5:
        train_res.append(1)
    else:
        train_res.append(0)
train_res = np.array(train_res).reshape(-1,1)
sum = 0
for i in range(len(train_res)):
    if int(train_res[i][0]) == int(Y[i][0]):
        sum += 1
print(sum/len(train_res))

0.7867564534231201


In [43]:
X_test = np.array(test[feature].values, dtype = float)
X_test = np.insert(X_test,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
X_test = X_test/np.max(X_test, axis=0)
X_test

array([[1.        , 0.        , 0.45394737],
       [1.        , 1.        , 0.61842105],
       [1.        , 0.        , 0.81578947],
       ...,
       [1.        , 0.        , 0.50657895],
       [1.        , 0.        , 0.27631579],
       [1.        , 0.        , 0.27631579]])

In [44]:
#predicting on test set
test_res = []
for num in range(len(X_test)):
    if sigmoid(np.dot(w.T,data[num])) >= 0.5:
        test_res.append(1)
    else:
        test_res.append(0)
test_res = np.array(test_res).reshape(-1,1)
print(test_res)

[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]


In [45]:
df_result = pd.DataFrame()
df_result = test[["PassengerId"]]
df_result["Survived"] = test_res.reshape(-1)
df_result

<ipython-input-45-1fd4da4a8654>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result["Survived"] = test_res.reshape(-1)


PassengerId  Survived
0            892         0
1            893         1
2            894         1
3            895         1
4            896         0
..           ...       ...
413         1305         0
414         1306         0
415         1307         1
416         1308         1
417         1309         1

[418 rows x 2 columns]

In [46]:
#df_result.to_csv("submission3.csv",index=False)

In [47]:
"""
after adding to kaggle. as you can see from the picture T9, the model accuracy can perform a bit better than T7.
It can be described that the more feature doesn't mean the more accuracy of model
"""

# OT2

In [48]:
import numpy as np
lr = 0.001
feature = ["Sex","Age"]
data = np.array(train[feature].values, dtype = float)
data = np.insert(data,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
data = data/np.max(data, axis=0)
w = np.random.rand(len(feature)+1).reshape(-1,1)
data

array([[1.   , 0.   , 0.275],
       [1.   , 1.   , 0.475],
       [1.   , 1.   , 0.325],
       ...,
       [1.   , 1.   , 0.3  ],
       [1.   , 0.   , 0.325],
       [1.   , 0.   , 0.4  ]])

In [49]:
for epoch in range(1000):
    print(f"epoch : {epoch}")
    for j in range(len(w)):
        sum = 0
        for num in range(len(data)):
            sum += (Y[num][0] - np.dot(w.T,data[num]))*data[num][j]
        print(sum)
        w[j] = w[j] + lr*sum

epoch : 0
[-107.16030854]
[106.00548174]
[-37.43211354]
epoch : 1
[-33.05662053]
[87.10383966]
[-31.07291327]
epoch : 2
[-21.0674755]
[69.69244621]
[-27.54221061]
epoch : 3
[-15.41682583]
[55.59622939]
[-24.78807816]
epoch : 4
[-11.25096045]
[44.32351961]
[-22.53311141]
epoch : 5
[-7.9747009]
[35.32047013]
[-20.66826059]
epoch : 6
[-5.38396064]
[28.13139332]
[-19.11569339]
epoch : 7
[-3.33817179]
[22.39122306]
[-17.8139768]
epoch : 8
[-1.72692752]
[17.80828443]
[-16.71407142]
epoch : 9
[-0.46221015]
[14.1496049]
[-15.77677936]
epoch : 10
[0.52625624]
[11.22910547]
[-14.97075934]
epoch : 11
[1.29458885]
[8.89816244]
[-14.27094569]
epoch : 12
[1.88759726]
[7.0380683]
[-13.6572859]
epoch : 13
[2.3410599]
[5.55401021]
[-13.11373235]
epoch : 14
[2.68354206]
[4.37026031]
[-12.62743692]
epoch : 15
[2.93784808]
[3.42633434]
[-12.18810772]
epoch : 16
[3.12218118]
[2.67392329]
[-11.78749526]
epoch : 17
[3.25106984]
[2.07444275]
[-11.41898208]
epoch : 18
[3.33610774]
[1.59707551]
[-11.07725487]
e

[0.13918499]
[-0.01126018]
[-0.36832173]
epoch : 160
[0.13589381]
[-0.01099392]
[-0.35961236]
epoch : 161
[0.13268045]
[-0.01073396]
[-0.35110893]
epoch : 162
[0.12954307]
[-0.01048014]
[-0.34280658]
epoch : 163
[0.12647989]
[-0.01023233]
[-0.33470054]
epoch : 164
[0.12348913]
[-0.00999037]
[-0.32678618]
epoch : 165
[0.1205691]
[-0.00975414]
[-0.31905896]
epoch : 166
[0.11771811]
[-0.00952349]
[-0.31151447]
epoch : 167
[0.11493453]
[-0.0092983]
[-0.30414836]
epoch : 168
[0.11221678]
[-0.00907843]
[-0.29695644]
epoch : 169
[0.10956329]
[-0.00886376]
[-0.28993458]
epoch : 170
[0.10697255]
[-0.00865417]
[-0.28307876]
epoch : 171
[0.10444307]
[-0.00844953]
[-0.27638506]
epoch : 172
[0.10197339]
[-0.00824973]
[-0.26984963]
epoch : 173
[0.09956212]
[-0.00805466]
[-0.26346874]
epoch : 174
[0.09720787]
[-0.0078642]
[-0.25723873]
epoch : 175
[0.09490928]
[-0.00767824]
[-0.25115604]
epoch : 176
[0.09266505]
[-0.00749668]
[-0.24521718]
epoch : 177
[0.09047388]
[-0.00731941]
[-0.23941875]
epoch : 

[-0.00860138]
epoch : 317
[0.00317352]
[-0.00025674]
[-0.008398]
epoch : 318
[0.00309847]
[-0.00025067]
[-0.00819942]
epoch : 319
[0.00302521]
[-0.00024474]
[-0.00800553]
epoch : 320
[0.00295367]
[-0.00023895]
[-0.00781623]
epoch : 321
[0.00288383]
[-0.0002333]
[-0.00763141]
epoch : 322
[0.00281564]
[-0.00022779]
[-0.00745096]
epoch : 323
[0.00274906]
[-0.0002224]
[-0.00727477]
epoch : 324
[0.00268406]
[-0.00021714]
[-0.00710275]
epoch : 325
[0.00262059]
[-0.00021201]
[-0.0069348]
epoch : 326
[0.00255862]
[-0.00020699]
[-0.00677082]
epoch : 327
[0.00249812]
[-0.0002021]
[-0.00661071]
epoch : 328
[0.00243905]
[-0.00019732]
[-0.0064544]
epoch : 329
[0.00238138]
[-0.00019266]
[-0.00630177]
epoch : 330
[0.00232507]
[-0.0001881]
[-0.00615276]
epoch : 331
[0.00227009]
[-0.00018365]
[-0.00600727]
epoch : 332
[0.00221641]
[-0.00017931]
[-0.00586522]
epoch : 333
[0.002164]
[-0.00017507]
[-0.00572654]
epoch : 334
[0.00211283]
[-0.00017093]
[-0.00559112]
epoch : 335
[0.00206287]
[-0.00016689]
[-0

[8.97477539e-05]
[-7.26066898e-06]
[-0.0002375]
epoch : 467
[8.762557e-05]
[-7.08898253e-06]
[-0.00023188]
epoch : 468
[8.55535675e-05]
[-6.92135577e-06]
[-0.0002264]
epoch : 469
[8.35305598e-05]
[-6.75769273e-06]
[-0.00022104]
epoch : 470
[8.15553882e-05]
[-6.59789969e-06]
[-0.00021582]
epoch : 471
[7.96269218e-05]
[-6.44188513e-06]
[-0.00021071]
epoch : 472
[7.77440561e-05]
[-6.2895597e-06]
[-0.00020573]
epoch : 473
[7.59057127e-05]
[-6.14083618e-06]
[-0.00020087]
epoch : 474
[7.41108391e-05]
[-5.9956294e-06]
[-0.00019612]
epoch : 475
[7.23584072e-05]
[-5.85385616e-06]
[-0.00019148]
epoch : 476
[7.06474134e-05]
[-5.71543531e-06]
[-0.00018695]
epoch : 477
[6.8976878e-05]
[-5.58028759e-06]
[-0.00018253]
epoch : 478
[6.73458442e-05]
[-5.44833559e-06]
[-0.00017822]
epoch : 479
[6.5753378e-05]
[-5.31950373e-06]
[-0.000174]
epoch : 480
[6.41985674e-05]
[-5.19371824e-06]
[-0.00016989]
epoch : 481
[6.2680522e-05]
[-5.07090709e-06]
[-0.00016587]
epoch : 482
[6.11983724e-05]
[-4.95099993e-06]


[-2.8705014e-07]
[-9.38943971e-06]
epoch : 602
[3.46427215e-06]
[-2.80262534e-07]
[-9.16741616e-06]
epoch : 603
[3.3823556e-06]
[-2.73635428e-07]
[-8.95064255e-06]
epoch : 604
[3.30237611e-06]
[-2.6716501e-07]
[-8.73899483e-06]
epoch : 605
[3.2242878e-06]
[-2.60847613e-07]
[-8.53235171e-06]
epoch : 606
[3.14804597e-06]
[-2.54679586e-07]
[-8.33059489e-06]
epoch : 607
[3.07360702e-06]
[-2.48657396e-07]
[-8.13360887e-06]
epoch : 608
[3.00092826e-06]
[-2.42777638e-07]
[-7.94128077e-06]
epoch : 609
[2.92996796e-06]
[-2.37036861e-07]
[-7.75350052e-06]
epoch : 610
[2.86068568e-06]
[-2.31431886e-07]
[-7.57016052e-06]
epoch : 611
[2.79304162e-06]
[-2.25959433e-07]
[-7.39115577e-06]
epoch : 612
[2.72699708e-06]
[-2.20616354e-07]
[-7.21638379e-06]
epoch : 613
[2.66251425e-06]
[-2.15399657e-07]
[-7.04574449e-06]
epoch : 614
[2.59955624e-06]
[-2.10306278e-07]
[-6.87914016e-06]
epoch : 615
[2.53808687e-06]
[-2.0533336e-07]
[-6.71647538e-06]
epoch : 616
[2.47807098e-06]
[-2.00478032e-07]
[-6.55765694

[-4.08499707e-07]
epoch : 733
[1.50717619e-07]
[-1.21931832e-08]
[-3.98840285e-07]
epoch : 734
[1.47153733e-07]
[-1.19048698e-08]
[-3.89409257e-07]
epoch : 735
[1.43674156e-07]
[-1.16233534e-08]
[-3.80201261e-07]
epoch : 736
[1.40276811e-07]
[-1.13485152e-08]
[-3.7121099e-07]
epoch : 737
[1.36959775e-07]
[-1.10801748e-08]
[-3.624333e-07]
epoch : 738
[1.33721259e-07]
[-1.08181735e-08]
[-3.53863168e-07]
epoch : 739
[1.30559241e-07]
[-1.05623675e-08]
[-3.45495691e-07]
epoch : 740
[1.27472035e-07]
[-1.03126173e-08]
[-3.37326049e-07]
epoch : 741
[1.24457838e-07]
[-1.00687502e-08]
[-3.29349601e-07]
epoch : 742
[1.21514898e-07]
[-9.83067949e-09]
[-3.21561787e-07]
epoch : 743
[1.18641529e-07]
[-9.59821556e-09]
[-3.13958106e-07]
epoch : 744
[1.15836101e-07]
[-9.37123656e-09]
[-3.06534205e-07]
epoch : 745
[1.13097103e-07]
[-9.14966247e-09]
[-2.99285886e-07]
epoch : 746
[1.10422735e-07]
[-8.93328111e-09]
[-2.9220894e-07]
epoch : 747
[1.07811709e-07]
[-8.72205319e-09]
[-2.85299355e-07]
epoch : 748

[-1.69417465e-08]
epoch : 866
[6.25071631e-09]
[-5.05713249e-10]
[-1.65411483e-08]
epoch : 867
[6.10292888e-09]
[-4.93751484e-10]
[-1.61500218e-08]
epoch : 868
[5.95860603e-09]
[-4.82080598e-10]
[-1.57681122e-08]
epoch : 869
[5.81771956e-09]
[-4.70676942e-10]
[-1.53952687e-08]
epoch : 870
[5.68014993e-09]
[-4.59553284e-10]
[-1.50312369e-08]
epoch : 871
[5.54584476e-09]
[-4.48700188e-10]
[-1.46757988e-08]
epoch : 872
[5.41472814e-09]
[-4.38065473e-10]
[-1.43287717e-08]
epoch : 873
[5.28668673e-09]
[-4.27699876e-10]
[-1.39899691e-08]
epoch : 874
[5.1616392e-09]
[-4.17596846e-10]
[-1.36591631e-08]
epoch : 875
[5.03958775e-09]
[-4.0772874e-10]
[-1.33361722e-08]
epoch : 876
[4.92041974e-09]
[-3.98093447e-10]
[-1.302081e-08]
epoch : 877
[4.80409382e-09]
[-3.88672872e-10]
[-1.27129307e-08]
epoch : 878
[4.69049866e-09]
[-3.79470566e-10]
[-1.24123182e-08]
epoch : 879
[4.57957136e-09]
[-3.70487974e-10]
[-1.21187983e-08]
epoch : 880
[4.47129048e-09]
[-3.61739305e-10]
[-1.18322445e-08]
epoch : 881

[-2.09792184e-11]
[-6.8601172e-10]


In [50]:
w

array([[ 0.20301973],
       [ 0.55215353],
       [-0.03855485]])

# OT3

In [51]:
XT_X_INV = np.linalg.inv(np.dot(data.T,data))
XT_Y = np.dot(data.T,Y)

In [52]:
w_mat = np.dot(XT_X_INV,XT_Y)
w_mat

array([[ 0.20301973],
       [ 0.55215353],
       [-0.03855485]])

In [59]:
sum_se_OT2 = 0
sum_se_OT3 = 0
for i in range(len(Y)):
    sum_se_OT2 += (Y[i] - np.dot(w.T,data[i]))**2
    sum_se_OT3 += (Y[i] - np.dot(w_mat.T,data[i]))**2
MSE_OT2 = sum_se_OT2 / len(data)
MSE_OT3 = sum_se_OT3 / len(data)
print(f"MSE of linear regression : {MSE_OT2[0]}")
print(f"MSE of inversion matrix : {MSE_OT3[0]}")
# quite similar
print(f"difference : {MSE_OT2[0]-MSE_OT3[0]}")

MSE of linear regression : 0.16664229654020138
MSE of inversion matrix : 0.16664229654020077
difference : 6.106226635438361e-16
