# Titanic

In [1]:
import pandas as pd
train_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/train.csv"
train = pd.read_csv(train_url)
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [2]:
test_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/test.csv"
test = pd.read_csv(test_url)
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [3]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [4]:
train["Age"].mode()

0    24.0
dtype: float64

# T4

In [5]:
train["Age"] = train["Age"].fillna(train["Age"].mode()[0])

In [6]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   28.566970    0.523008   
std     257.353842    0.486592    0.836071   13.199572    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   24.000000    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [7]:
print(pd.unique(train["Embarked"]))
print(train["Embarked"].isna().sum())

['S' 'C' 'Q' nan]
2


# T5

In [8]:
train.loc[train["Embarked"] == "S", "Embarked"] = 0
train.loc[train["Embarked"] == "C", "Embarked"] = 1
train.loc[train["Embarked"] == "Q", "Embarked"] = 2
train["Embarked"] = train["Embarked"].fillna(train["Embarked"].mode()[0])

In [9]:
print(pd.unique(train["Sex"]))

['male' 'female']


In [10]:
train.loc[train["Sex"] == "male", "Sex"] = 0
train.loc[train["Sex"] == "female", "Sex"] = 1

# T6

In [11]:
import numpy as np
lr = 0.01
feature = ["Pclass","Sex","Age","Embarked"]
data = np.array(train[feature].values, dtype = float)
data = np.insert(data,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
data_unnorm = data
data

array([[ 1.,  3.,  0., 22.,  0.],
       [ 1.,  1.,  1., 38.,  1.],
       [ 1.,  3.,  1., 26.,  0.],
       ...,
       [ 1.,  3.,  1., 24.,  0.],
       [ 1.,  1.,  0., 26.,  1.],
       [ 1.,  3.,  0., 32.,  2.]])

In [12]:
data = data/np.max(data, axis=0)
data

array([[1.        , 1.        , 0.        , 0.275     , 0.        ],
       [1.        , 0.33333333, 1.        , 0.475     , 0.5       ],
       [1.        , 1.        , 1.        , 0.325     , 0.        ],
       ...,
       [1.        , 1.        , 1.        , 0.3       , 0.        ],
       [1.        , 0.33333333, 0.        , 0.325     , 0.5       ],
       [1.        , 1.        , 0.        , 0.4       , 1.        ]])

In [13]:
Y = np.array(train[["Survived"]].values, dtype = float)

In [14]:
w = np.random.rand(len(feature)+1).reshape(-1,1)
w

array([[0.06835539],
       [0.56091274],
       [0.57612018],
       [0.35992217],
       [0.29454974]])

In [15]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [16]:
for epoch in range(1000):
    for j in range(len(w)):
        sum = 0
        for num in range(len(data)):
            sum += (Y[num][0] - sigmoid(np.dot(w.T,data[num])))*data[num][j]
        w[j] = w[j] + lr*sum

In [17]:
#predicting on train set
train_res = []
for num in range(len(data)):
    if sigmoid(np.dot(w.T,data[num])) >= 0.5:
        train_res.append(1)
    else:
        train_res.append(0)

In [18]:
train_res = np.array(train_res).reshape(-1,1)

In [19]:
sum = 0
for i in range(len(train_res)):
    if int(train_res[i][0]) == int(Y[i][0]):
        sum += 1
print(sum/len(train_res))

0.7811447811447811


In [20]:
test.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [21]:
test["Age"] = test["Age"].fillna(test["Age"].mode()[0])
print(pd.unique(test["Embarked"]))
print(test["Embarked"].isna().sum())

['Q' 'S' 'C']
0


In [22]:
test.loc[test["Embarked"] == "S", "Embarked"] = 0
test.loc[test["Embarked"] == "C", "Embarked"] = 1
test.loc[test["Embarked"] == "Q", "Embarked"] = 2
test["Embarked"] = test["Embarked"].fillna(test["Embarked"].mode()[0])
print(pd.unique(test["Sex"]))

['male' 'female']


In [23]:
test.loc[test["Sex"] == "male", "Sex"] = 0
test.loc[test["Sex"] == "female", "Sex"] = 1

In [24]:
X_test = np.array(test[feature].values, dtype = float)
X_test = np.insert(X_test,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
X_test = X_test/np.max(data_unnorm, axis=0)
X_test

array([[1.        , 1.        , 0.        , 0.43125   , 1.        ],
       [1.        , 1.        , 1.        , 0.5875    , 0.        ],
       [1.        , 0.66666667, 0.        , 0.775     , 1.        ],
       ...,
       [1.        , 1.        , 0.        , 0.48125   , 0.        ],
       [1.        , 1.        , 0.        , 0.2625    , 0.        ],
       [1.        , 1.        , 0.        , 0.2625    , 0.5       ]])

In [25]:
test

PassengerId  Pclass                                          Name Sex  \
0            892       3                              Kelly, Mr. James   0   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   1   
2            894       2                     Myles, Mr. Thomas Francis   0   
3            895       3                              Wirz, Mr. Albert   0   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   1   
..           ...     ...                                           ...  ..   
413         1305       3                            Spector, Mr. Woolf   0   
414         1306       1                  Oliva y Ocana, Dona. Fermina   1   
415         1307       3                  Saether, Mr. Simon Sivertsen   0   
416         1308       3                           Ware, Mr. Frederick   0   
417         1309       3                      Peter, Master. Michael J   0   

      Age  SibSp  Parch              Ticket      Fare Cabin  Embarked  
0    34.5      0      0              330911    7.8292   NaN         2  
1    47.0      1      0              363272    7.0000   NaN         0  
2    62.0      0      0              240276    9.6875   NaN         2  
3    27.0      0      0              315154    8.6625   NaN         0  
4    22.0      1      1             3101298   12.2875   NaN         0  
..    ...    ...    ...                 ...       ...   ...       ...  
413  21.0      0      0           A.5. 3236    8.0500   NaN         0  
414  39.0      0      0            PC 17758  108.9000  C105         1  
415  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN         0  
416  21.0      0      0              359309    8.0500   NaN         0  
417  21.0      1      1                2668   22.3583   NaN         1  

[418 rows x 11 columns]

In [26]:
#predicting on test set
test_res = []
for num in range(len(X_test)):
    if sigmoid(np.dot(w.T,X_test[num])) >= 0.5:
        test_res.append(1)
    else:
        test_res.append(0)
test_res = np.array(test_res).reshape(-1,1)

# T7

In [27]:
df_result = pd.DataFrame()
df_result = test[["PassengerId"]]
df_result["Survived"] = test_res.reshape(-1)
df_result

<ipython-input-27-1fd4da4a8654>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result["Survived"] = test_res.reshape(-1)


PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [28]:
#df_result.to_csv("submission.csv",index=False)

# T8

In [29]:
x1_x2 = []
x1_2 = []
for i in data_unnorm:
    x1_x2.append(i[1]*i[2])
    x1_2.append(i[1]**2)
data_unnorm = np.insert(data_unnorm,1,np.array(x1_x2),axis=1)
data_unnorm = np.insert(data_unnorm,1,np.array(x1_2),axis=1)
data = data_unnorm/np.max(data_unnorm, axis=0)
data

array([[1.        , 1.        , 0.        , ..., 0.        , 0.275     ,
        0.        ],
       [1.        , 0.11111111, 0.33333333, ..., 1.        , 0.475     ,
        0.5       ],
       [1.        , 1.        , 1.        , ..., 1.        , 0.325     ,
        0.        ],
       ...,
       [1.        , 1.        , 1.        , ..., 1.        , 0.3       ,
        0.        ],
       [1.        , 0.11111111, 0.        , ..., 0.        , 0.325     ,
        0.5       ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.4       ,
        1.        ]])

In [30]:
w = np.random.rand(data.shape[1]).reshape(-1,1)
w

array([[0.98012623],
       [0.14325524],
       [0.42502784],
       [0.42319849],
       [0.56163902],
       [0.12375004],
       [0.65407678]])

In [31]:
for epoch in range(1000):
    for j in range(len(w)):
        sum = 0
        for num in range(len(data)):
            sum += (Y[num][0] - sigmoid(np.dot(w.T,data[num])))*data[num][j]
        w[j] = w[j] + lr*sum

In [32]:
#predicting on train set
train_res = []
for num in range(len(data)):
    if sigmoid(np.dot(w.T,data[num])) >= 0.5:
        train_res.append(1)
    else:
        train_res.append(0)
train_res = np.array(train_res).reshape(-1,1)
sum = 0
for i in range(len(train_res)):
    if int(train_res[i][0]) == int(Y[i][0]):
        sum += 1
print(f"accuracy : {sum/len(train_res)}")
# a bit better than before

accuracy : 0.8013468013468014


In [33]:
feature = ["Pclass","Sex","Age","Embarked"]
X_test = np.array(test[feature].values, dtype = float)
X_test = np.insert(X_test,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
X_test

array([[ 1. ,  3. ,  0. , 34.5,  2. ],
       [ 1. ,  3. ,  1. , 47. ,  0. ],
       [ 1. ,  2. ,  0. , 62. ,  2. ],
       ...,
       [ 1. ,  3. ,  0. , 38.5,  0. ],
       [ 1. ,  3. ,  0. , 21. ,  0. ],
       [ 1. ,  3. ,  0. , 21. ,  1. ]])

In [34]:
x1_x2 = []
x1_2 = []
for i in X_test:
    x1_x2.append(i[1]*i[2])
    x1_2.append(i[1]**2)
X_test = np.insert(X_test,1,np.array(x1_x2),axis=1)
X_test = np.insert(X_test,1,np.array(x1_2),axis=1)
X_test = X_test/np.max(data_unnorm, axis=0)
X_test

array([[1.        , 1.        , 0.        , ..., 0.        , 0.43125   ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 0.5875    ,
        0.        ],
       [1.        , 0.44444444, 0.        , ..., 0.        , 0.775     ,
        1.        ],
       ...,
       [1.        , 1.        , 0.        , ..., 0.        , 0.48125   ,
        0.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.2625    ,
        0.        ],
       [1.        , 1.        , 0.        , ..., 0.        , 0.2625    ,
        0.5       ]])

In [35]:
#predicting on test set
test_res = []
for num in range(len(X_test)):
    if sigmoid(np.dot(w.T,X_test[num])) >= 0.5:
        test_res.append(1)
    else:
        test_res.append(0)
test_res = np.array(test_res).reshape(-1,1)

In [36]:
df_result = pd.DataFrame()
df_result = test[["PassengerId"]]
df_result["Survived"] = test_res.reshape(-1)
df_result

<ipython-input-36-1fd4da4a8654>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result["Survived"] = test_res.reshape(-1)


PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [37]:
#df_result.to_csv("submission2.csv",index=False)

In [38]:
"""
after adding to kaggle. as you can see from the picture T8, 
the model doesn't overfitting to train set as my assumption (before fitting) 
and model a bit better accuracy than T6
"""

"\nafter adding to kaggle. as you can see from the picture T8, \nthe model doesn't overfitting to train set as my assumption (before fitting) \nand model a bit better accuracy than T6\n"

# T9

In [39]:
import numpy as np
lr = 0.01
feature = ["Sex","Age"]
data = np.array(train[feature].values, dtype = float)
data = np.insert(data,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
data_unnorm = data
data = data/np.max(data, axis=0)
w = np.random.rand(len(feature)+1).reshape(-1,1)
data


array([[1.   , 0.   , 0.275],
       [1.   , 1.   , 0.475],
       [1.   , 1.   , 0.325],
       ...,
       [1.   , 1.   , 0.3  ],
       [1.   , 0.   , 0.325],
       [1.   , 0.   , 0.4  ]])

In [40]:
for epoch in range(1000):
    for j in range(len(w)):
        sum = 0
        for num in range(len(data)):
            sum += (Y[num][0] - sigmoid(np.dot(w.T,data[num])))*data[num][j]
        w[j] = w[j] + lr*sum

In [41]:
w

array([[-1.37227573],
       [ 2.50861377],
       [-0.23307829]])

In [42]:
#predicting on train set
train_res = []
for num in range(len(data)):
    if sigmoid(np.dot(data[num],w)) >= 0.5:
        train_res.append(1)
    else:
        train_res.append(0)
train_res = np.array(train_res).reshape(-1,1)
sum = 0
for i in range(len(train_res)):
    if int(train_res[i][0]) == int(Y[i][0]):
        sum += 1
print(sum/len(train_res))

0.7867564534231201


In [43]:
X_test = np.array(test[feature].values, dtype = float)
X_test = np.insert(X_test,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
X_test = X_test/np.max(data_unnorm, axis=0)
X_test

array([[1.     , 0.     , 0.43125],
       [1.     , 1.     , 0.5875 ],
       [1.     , 0.     , 0.775  ],
       ...,
       [1.     , 0.     , 0.48125],
       [1.     , 0.     , 0.2625 ],
       [1.     , 0.     , 0.2625 ]])

In [44]:
#predicting on test set
test_res = []
for num in range(len(X_test)):
    if sigmoid(np.dot(w.T,data[num])) >= 0.5:
        test_res.append(1)
    else:
        test_res.append(0)
test_res = np.array(test_res).reshape(-1,1)

In [45]:
df_result = pd.DataFrame()
df_result = test[["PassengerId"]]
df_result["Survived"] = test_res.reshape(-1)
df_result

<ipython-input-45-1fd4da4a8654>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result["Survived"] = test_res.reshape(-1)


PassengerId  Survived
0            892         0
1            893         1
2            894         1
3            895         1
4            896         0
..           ...       ...
413         1305         0
414         1306         0
415         1307         1
416         1308         1
417         1309         1

[418 rows x 2 columns]

In [46]:
#df_result.to_csv("submission3.csv",index=False)

In [47]:
"""
after adding to kaggle. as you can see from the picture T9, the model accuracy can perform a bit better than T7.
It can be described that the more feature doesn't mean the more accuracy of model
"""

"\nafter adding to kaggle. as you can see from the picture T9, the model accuracy can perform a bit better than T7.\nIt can be described that the more feature doesn't mean the more accuracy of model\n"

# OT2

In [48]:
import numpy as np
lr = 0.001
feature = ["Sex","Age"]
data = np.array(train[feature].values, dtype = float)
data = np.insert(data,0,1,axis=1) # (x0)=1 x1 x2 x3 x4
data = data/np.max(data, axis=0)
w = np.random.rand(len(feature)+1).reshape(-1,1)
data

array([[1.   , 0.   , 0.275],
       [1.   , 1.   , 0.475],
       [1.   , 1.   , 0.325],
       ...,
       [1.   , 1.   , 0.3  ],
       [1.   , 0.   , 0.325],
       [1.   , 0.   , 0.4  ]])

In [49]:
for epoch in range(1000):
    for j in range(len(w)):
        sum = 0
        for num in range(len(data)):
            sum += (Y[num][0] - np.dot(w.T,data[num]))*data[num][j]
        w[j] = w[j] + lr*sum

In [50]:
w

array([[ 0.20301973],
       [ 0.55215353],
       [-0.03855485]])

# OT3

In [51]:
XT_X_INV = np.linalg.inv(np.dot(data.T,data))
XT_Y = np.dot(data.T,Y)

In [52]:
w_mat = np.dot(XT_X_INV,XT_Y)
w_mat

array([[ 0.20301973],
       [ 0.55215353],
       [-0.03855485]])

In [53]:
sum_se_OT2 = 0
sum_se_OT3 = 0
for i in range(len(Y)):
    sum_se_OT2 += (Y[i] - np.dot(w.T,data[i]))**2
    sum_se_OT3 += (Y[i] - np.dot(w_mat.T,data[i]))**2
MSE_OT2 = sum_se_OT2 / len(data)
MSE_OT3 = sum_se_OT3 / len(data)
print(f"MSE of linear regression : {MSE_OT2[0]}")
print(f"MSE of inversion matrix : {MSE_OT3[0]}")
# quite similar
print(f"difference : {MSE_OT2[0]-MSE_OT3[0]}")

MSE of linear regression : 0.16664229654020063
MSE of inversion matrix : 0.16664229654020077
difference : -1.3877787807814457e-16
